import type { Exam, Question } from './exams';
import { semesterOneExams10 } from './exams10-semester1';

const q = (id: number, prompt: string, options: string[], answer: number, explanation: string, underlines?: string[]): Question => ({
  id,
  section: 'Language Focus',
  prompt,
  options,
  answer,
  explanation,
  underlines,
});

export const exams10: Exam[] = [
  {
    id: 1,
    menuLabel: 'Unit 1 · Family Life',
    menuGroup: 'unit',
    title: 'Unit 1 · Family Life',
    theme: 'Vocabulary · Present tenses · /br/, /kr/, /tr/',
    sourceNote: 'Bài mẫu được biên soạn mới theo ba chủ điểm công khai của Unit 1 trên Loigiaihay: Family Life, thì hiện tại đơn–hiện tại tiếp diễn và các cụm phụ âm /br/, /kr/, /tr/.',
    passageTitle: '',
    passage: '',
    reviewNotes: [
      { title: 'Hiện tại đơn', rule: 'Dùng cho thói quen, lịch trình và sự thật. Với he/she/it, động từ thường thêm -s/-es.', example: 'My father cooks dinner every Friday.' },
      { title: 'Hiện tại tiếp diễn', rule: 'Dùng am/is/are + V-ing cho hành động đang xảy ra hoặc tình huống tạm thời. Các dấu hiệu thường gặp: now, right now, at the moment.', example: 'My sister is washing the dishes now.' },
      { title: 'Động từ trạng thái', rule: 'Các động từ như know, understand, believe, love, need thường không dùng ở thì tiếp diễn.', example: 'I understand the problem.' },
      { title: 'Cụm phụ âm', rule: '/br/, /kr/ và /tr/ được phát âm liền mạch, không chèn thêm nguyên âm ở giữa hai phụ âm.', example: 'bread /bred/ · cream /kriːm/ · tree /triː/' },
    ],
    questions: [
      q(1, 'Parents should divide household ___ fairly.', ['chores', 'benefits', 'opinions', 'systems'], 0, '“Household chores” là cụm cố định, nghĩa là các công việc nhà như nấu ăn, lau dọn và giặt quần áo.'),
      q(2, 'My father is the main ___, but everyone shares the housework.', ['breadwinner', 'homemaker', 'relative', 'teenager'], 0, '“Breadwinner” là người kiếm phần lớn thu nhập để nuôi gia đình. “Homemaker” là người chủ yếu chăm sóc nhà cửa.'),
      q(3, 'Doing chores teaches children to take ___.', ['responsible', 'responsibility', 'responsibly', 'response'], 1, 'Cụm “take responsibility” nghĩa là nhận hoặc có trách nhiệm. Sau “take” cần danh từ “responsibility”.'),
      q(4, 'Lan usually ___ the washing-up after dinner.', ['does', 'makes', 'takes', 'works'], 0, 'Cụm đúng là “do the washing-up” = rửa bát. Chủ ngữ Lan là ngôi thứ ba số ít nên “do” đổi thành “does”.'),
      q(5, 'Parents can strengthen family ___ by spending time together.', ['bonds', 'duties', 'routines', 'laundry'], 0, '“Family bonds” là mối quan hệ gắn bó giữa các thành viên. “Strengthen family bonds” nghĩa là tăng sự gắn kết gia đình.'),
      q(6, 'A person who manages the home and cares for the family is a ___.', ['breadwinner', 'homemaker', 'household', 'provider'], 1, '“Homemaker” chỉ người quản lý việc nhà và chăm sóc gia đình, không nhất thiết là người tạo thu nhập chính.'),
      q(7, 'Sharing chores reduces the ___ on one family member.', ['burden', 'value', 'support', 'benefit'], 0, '“Burden” nghĩa là gánh nặng. Khi mọi người chia việc, gánh nặng đặt lên một người sẽ giảm.'),
      q(8, 'My brother takes out the ___ every evening.', ['rubbish', 'furniture', 'groceries', 'washing-up'], 0, 'Cụm “take out the rubbish” nghĩa là mang rác ra ngoài. Đây là một công việc nhà thông dụng.'),
      q(9, 'Children learn useful life ___ when they help at home.', ['skills', 'chores', 'benefits', 'roles'], 0, '“Life skills” là các kỹ năng cần thiết trong cuộc sống. Làm việc nhà giúp trẻ học tính tự lập và tổ chức.'),
      q(10, 'We bought food and household items at the supermarket. “Household” is closest in meaning to ___.', ['related to a home', 'related to a school', 'expensive', 'traditional'], 0, 'Trong “household items”, household có nghĩa là thuộc hoặc dùng trong gia đình/nhà ở.'),

      q(11, 'My mother usually ___ breakfast at 6:30.', ['prepares', 'is preparing', 'prepare', 'preparing'], 0, '“Usually” diễn tả thói quen nên dùng hiện tại đơn. Chủ ngữ số ít “my mother” đi với “prepares”.'),
      q(12, 'Listen! Someone ___ at the front door.', ['knocks', 'is knocking', 'knock', 'knocked'], 1, '“Listen!” cho thấy hành động đang xảy ra ngay lúc nói, nên dùng hiện tại tiếp diễn: is knocking.'),
      q(13, 'We ___ the living room every Saturday.', ['clean', 'are cleaning', 'cleans', 'cleaning'], 0, '“Every Saturday” là lịch lặp lại, vì vậy dùng hiện tại đơn. Chủ ngữ “we” đi với động từ nguyên mẫu “clean”.'),
      q(14, 'Dad cannot answer the phone because he ___ dinner now.', ['cooks', 'is cooking', 'cook', 'cooked'], 1, 'Có “now” và hành động đang diễn ra, nên dùng “is cooking”.'),
      q(15, 'My grandparents ___ with us this month while their house is repaired.', ['stay', 'are staying', 'stays', 'stayed'], 1, '“This month” cùng ngữ cảnh tạm thời cho thấy cần hiện tại tiếp diễn: are staying.'),
      q(16, 'Hoa ___ why sharing chores is important.', ['understands', 'is understanding', 'understand', 'understanding'], 0, '“Understand” là động từ trạng thái, thường không dùng ở thì tiếp diễn. Hoa là số ít nên dùng “understands”.'),
      q(17, 'What ___ your sister usually ___ after school?', ['does / do', 'is / doing', 'do / does', 'does / doing'], 0, 'Câu hỏi về thói quen dùng “does + chủ ngữ số ít + V nguyên mẫu”: does your sister do.'),
      q(18, 'Why ___ you ___ the floor at the moment?', ['do / sweep', 'are / sweeping', 'does / sweep', 'are / sweep'], 1, '“At the moment” yêu cầu hiện tại tiếp diễn. Với “you”, cấu trúc là “are + V-ing”.'),
      q(19, 'Normally Minh cooks, but today his sister ___ dinner.', ['makes', 'is making', 'make', 'made'], 1, '“Today” diễn tả sự thay đổi tạm thời so với thói quen “normally”, nên dùng hiện tại tiếp diễn.'),
      q(20, 'Our school bus ___ at 6:45 every morning.', ['is leaving', 'leave', 'leaves', 'leaving'], 2, 'Lịch trình cố định dùng hiện tại đơn. Chủ ngữ “bus” là số ít nên dùng “leaves”.'),

      q(21, 'Choose the word whose underlined part is pronounced differently.', ['bread', 'breakfast', 'brown', 'climb'], 3, 'Bread, breakfast và brown bắt đầu bằng cụm /br/. “Climb” bắt đầu bằng /kl/, nên chọn D.', ['br', 'br', 'br', 'cl']),
      q(22, 'Choose the word whose underlined part is pronounced differently.', ['cream', 'crane', 'create', 'brush'], 3, 'Cream, crane và create bắt đầu bằng /kr/. “Brush” bắt đầu bằng /br/.', ['cr', 'cr', 'cr', 'br']),
      q(23, 'Choose the word whose underlined part is pronounced differently.', ['tree', 'train', 'treat', 'cream'], 3, 'Tree, train và treat bắt đầu bằng /tr/. “Cream” bắt đầu bằng /kr/.', ['tr', 'tr', 'tr', 'cr']),
      q(24, 'Which word begins with the /br/ sound?', ['crowd', 'brother', 'train', 'clean'], 1, '“Brother” /ˈbrʌðə/ bắt đầu bằng cụm phụ âm /br/. Các từ còn lại lần lượt bắt đầu bằng /kr/, /tr/ và /kl/.', ['cr', 'br', 'tr', 'cl']),
      q(25, 'Which word begins with the /kr/ sound?', ['breadwinner', 'traffic', 'creative', 'practice'], 2, '“Creative” /kriˈeɪtɪv/ bắt đầu bằng /kr/. Breadwinner bắt đầu /br/, traffic bắt đầu /tr/, practice bắt đầu /pr/.', ['br', 'tr', 'cr', 'pr']),
    ],
  },
  {
    id: 2,
    menuLabel: 'Unit 2 · Humans and the Environment',
    menuGroup: 'unit',
    title: 'Unit 2 · Humans and the Environment',
    theme: 'Environment · Future forms · Passive voice · /kl/, /pl/, /gr/, /pr/',
    sourceNote: 'Bài được biên soạn mới theo các chủ điểm công khai của Unit 2: hoạt động của con người và môi trường, will/be going to, câu bị động và các cụm phụ âm /kl/, /pl/, /gr/, /pr/.',
    passageTitle: '', passage: '',
    reviewNotes: [
      { title: 'Will và be going to', rule: 'Will thường dùng cho quyết định tức thời, dự đoán hoặc lời hứa; be going to dùng cho kế hoạch đã có hoặc dự đoán có dấu hiệu rõ.', example: 'Look at those clouds! It is going to rain.' },
      { title: 'Câu bị động', rule: 'S + be + V3/ed. Thì của động từ be thay đổi theo thời gian; tác nhân có thể đặt sau by.', example: 'Plastic bottles are recycled here.' },
      { title: 'Cụm phụ âm', rule: 'Phát âm liền hai phụ âm trong /kl/, /pl/, /gr/, /pr/ mà không thêm nguyên âm.', example: 'clean · plant · green · protect' },
    ],
    questions: [
      q(1, 'We should reduce our carbon ___.', ['footprint', 'rubbish', 'resource', 'device'], 0, '“Carbon footprint” là lượng khí nhà kính do một người hoặc hoạt động tạo ra.'),
      q(2, 'Solar and wind power are ___ sources of energy.', ['renewable', 'single-use', 'polluted', 'harmful'], 0, 'Năng lượng mặt trời và gió có thể tái tạo tự nhiên nên được gọi là “renewable energy”.'),
      q(3, 'Many sea animals are harmed by plastic ___.', ['pollution', 'solution', 'protection', 'production'], 0, '“Plastic pollution” là ô nhiễm do rác nhựa, gây hại cho sinh vật biển.'),
      q(4, 'Turning off unused lights helps ___ energy.', ['save', 'waste', 'damage', 'release'], 0, '“Save energy” nghĩa là tiết kiệm năng lượng; tắt thiết bị không dùng là một cách thực hiện.'),
      q(5, 'Trees absorb carbon dioxide and ___ oxygen.', ['release', 'destroy', 'consume', 'pollute'], 0, 'Cây hấp thụ CO₂ và giải phóng “release” khí oxygen.'),
      q(6, 'A reusable bottle creates less ___ than a disposable one.', ['waste', 'wildlife', 'climate', 'electricity'], 0, 'Đồ tái sử dụng tạo ra ít rác thải hơn, nên danh từ phù hợp là “waste”.'),
      q(7, 'We can ___ old paper, glass and metal.', ['recycle', 'damage', 'throw', 'consume'], 0, '“Recycle” nghĩa là tái chế vật liệu đã qua sử dụng thành sản phẩm mới.'),
      q(8, 'The natural home of an animal is its ___.', ['habitat', 'footprint', 'landfill', 'resource'], 0, '“Habitat” là môi trường sống tự nhiên của động vật hoặc thực vật.'),
      q(9, 'I think people ___ use more electric vehicles in the future.', ['will', 'are going', 'were', 'have'], 0, 'Đây là dự đoán về tương lai dựa trên ý kiến “I think”, nên dùng “will + V”.'),
      q(10, 'We have bought the seeds. We ___ plant trees this Sunday.', ['are going to', 'will to', 'going', 'are planting to'], 0, 'Việc mua hạt giống cho thấy kế hoạch đã chuẩn bị, nên dùng “be going to + V”.'),
      q(11, 'The phone is ringing. I ___ answer it.', ['will', 'am going to', 'was', 'have'], 0, 'Quyết định được đưa ra ngay tại lúc nói nên dùng “will”.'),
      q(12, 'Look at that black smoke! The machine ___ break down.', ['is going to', 'will to', 'going to', 'is breaking to'], 0, 'Có dấu hiệu hiện tại rõ ràng nên dự đoán bằng “is going to”.'),
      q(13, 'I promise I ___ leave any rubbish in the park.', ['will not', 'am not going', 'do not', 'not will'], 0, 'Lời hứa thường dùng “will”; phủ định là “will not + V”.'),
      q(14, 'What ___ you going to do with these old clothes?', ['are', 'will', 'do', 'have'], 0, 'Cấu trúc câu hỏi của be going to: “What + are + you + going to + V?”'),
      q(15, 'Glass bottles ___ in this factory.', ['are recycled', 'recycle', 'are recycling', 'recycled'], 0, 'Chai thủy tinh nhận hành động, nên dùng hiện tại đơn bị động: are + V3.'),
      q(16, 'A new community garden ___ last year.', ['was created', 'created', 'is created', 'was creating'], 0, '“Last year” yêu cầu quá khứ; chủ ngữ nhận hành động nên dùng “was created”.'),
      q(17, 'More trees ___ next month.', ['will be planted', 'will plant', 'are plant', 'will be planting by'], 0, 'T lai bị động: will + be + V3, nên dùng “will be planted”.'),
      q(18, 'The river ___ by untreated waste.', ['is polluted', 'pollutes', 'is polluting', 'polluted'], 0, 'Con sông là đối tượng bị ô nhiễm; hiện tại đơn bị động là “is polluted”.'),
      q(19, 'These bags ___ from recycled materials.', ['are made', 'make', 'are making', 'made'], 0, 'Cụm bị động “be made from” dùng khi vật liệu đã biến đổi trong quá trình sản xuất.'),
      q(20, 'Who ___ the recycling programme organised by?', ['was', 'did', 'has', 'were'], 0, 'Câu hỏi bị động quá khứ với chủ ngữ số ít “programme”: was ... organised by?'),
      q(21, 'Choose the word whose underlined part is pronounced differently.', ['clean', 'class', 'place', 'climate'], 2, 'Clean, class và climate bắt đầu bằng /kl/; “place” bắt đầu bằng /pl/.', ['cl', 'cl', 'pl', 'cl']),
      q(22, 'Choose the word whose underlined part is pronounced differently.', ['plant', 'plastic', 'please', 'green'], 3, 'Plant, plastic và please bắt đầu bằng /pl/; green bắt đầu bằng /gr/.', ['pl', 'pl', 'pl', 'gr']),
      q(23, 'Choose the word whose underlined part is pronounced differently.', ['green', 'grow', 'group', 'protect'], 3, 'Green, grow và group bắt đầu bằng /gr/; protect bắt đầu bằng /pr/.', ['gr', 'gr', 'gr', 'pr']),
      q(24, 'Which word begins with /pr/?', ['cleaner', 'planet', 'programme', 'ground'], 2, '“Programme” bắt đầu bằng cụm /pr/; các từ khác lần lượt bắt đầu bằng /kl/, /pl/ và /gr/.', ['cl', 'pl', 'pr', 'gr']),
      q(25, 'Which word begins with /gr/?', ['climate', 'product', 'glass', 'greenhouse'], 3, '“Greenhouse” bắt đầu bằng /gr/. Climate /kl/, product /pr/, glass /ɡl/.', ['cl', 'pr', 'gl', 'gr']),
    ],
  },
  {
    id: 3,
    menuLabel: 'Unit 3 · Music',
    menuGroup: 'unit',
    title: 'Unit 3 · Music',
    theme: 'Music · Compound sentences · To-infinitive and bare infinitive · Word stress',
    sourceNote: 'Bài được biên soạn mới theo các chủ điểm công khai của Unit 3: từ vựng âm nhạc, câu ghép, to-infinitive/động từ nguyên mẫu và trọng âm từ hai âm tiết.',
    passageTitle: '', passage: '',
    reviewNotes: [
      { title: 'Câu ghép', rule: 'Dùng and, but, or, so, yet để nối hai mệnh đề độc lập; dùng dấu phẩy trước liên từ khi cần.', example: 'The song is simple, but it is moving.' },
      { title: 'To V và nguyên mẫu', rule: 'Một số động từ đi với to V như decide, hope, want; động từ khuyết thiếu và let/make thường đi với V nguyên mẫu không to.', example: 'She hopes to perform. / Music makes me relax.' },
      { title: 'Trọng âm hai âm tiết', rule: 'Nhiều danh từ/tính từ nhấn âm đầu; nhiều động từ nhấn âm sau, nhưng cần học theo từng từ.', example: 'REcord (n) · reCORD (v)' },
    ],
    questions: [
      q(1, 'The singer gave a live ___ in front of thousands of fans.', ['performance', 'audience', 'instrument', 'melody'], 0, '“Give a performance” nghĩa là biểu diễn; “live performance” là buổi biểu diễn trực tiếp.'),
      q(2, 'The people watching a concert are the ___.', ['audience', 'judges', 'artists', 'composers'], 0, '“Audience” là khán giả của một buổi biểu diễn.'),
      q(3, 'A person who writes music is a ___.', ['composer', 'singer', 'viewer', 'volunteer'], 0, '“Composer” là nhà soạn nhạc — người sáng tác phần nhạc.'),
      q(4, 'The song has a catchy ___.', ['melody', 'stage', 'contest', 'programme'], 0, '“Melody” là giai điệu; “catchy melody” là giai điệu dễ nhớ.'),
      q(5, 'The band will ___ their new album next week.', ['release', 'performer', 'talent', 'judge'], 0, '“Release an album” nghĩa là phát hành một album.'),
      q(6, 'She became famous after winning a singing ___.', ['contest', 'instrument', 'melody', 'concert'], 0, '“Singing contest” là cuộc thi hát; chiến thắng có thể giúp thí sinh được biết đến.'),
      q(7, 'The musician can play several musical ___.', ['instruments', 'audiences', 'stages', 'lyrics'], 0, '“Musical instruments” nghĩa là nhạc cụ.'),
      q(8, 'The words of a song are called its ___.', ['lyrics', 'rhythm', 'album', 'voice'], 0, '“Lyrics” là phần lời của bài hát.'),
      q(9, 'The judges praised her natural musical ___.', ['talent', 'release', 'concert', 'genre'], 0, '“Musical talent” là tài năng âm nhạc; “natural talent” là năng khiếu bẩm sinh.'),
      q(10, 'The tune is cheerful, ___ the lyrics are rather sad.', ['but', 'so', 'and', 'or'], 0, 'Hai mệnh đề tương phản: giai điệu vui nhưng lời buồn, nên dùng “but”.'),
      q(11, 'The hall was full, ___ we watched the concert online.', ['so', 'but', 'or', 'and'], 0, 'Mệnh đề sau là kết quả của việc hết chỗ, nên dùng “so”.'),
      q(12, 'Hurry up, ___ we will miss the opening song.', ['or', 'and', 'so', 'for'], 0, '“Mệnh lệnh + or + kết quả xấu” mang nghĩa nếu không nhanh lên thì sẽ bỏ lỡ.'),
      q(13, 'The singer writes songs, ___ she also plays the guitar.', ['and', 'but', 'or', 'yet'], 0, 'Hai ý bổ sung cùng chiều nên dùng “and”.'),
      q(14, 'The song is old, ___ young listeners still love it.', ['yet', 'so', 'and', 'for'], 0, '“Yet” nối hai ý tương phản, gần nghĩa “but”.'),
      q(15, 'Choose the correctly punctuated sentence.', ['The show ended, and we went home.', 'The show ended and, we went home.', 'The show, ended and we went home.', 'The show ended, or, we went home.'], 0, 'Khi nối hai mệnh đề độc lập bằng “and”, dấu phẩy được đặt trước liên từ.'),
      q(16, 'Mai hopes ___ on a large stage one day.', ['to perform', 'perform', 'performing', 'performed'], 0, '“Hope + to V” diễn tả hy vọng làm điều gì.'),
      q(17, 'The teacher made us ___ the chorus again.', ['sing', 'to sing', 'singing', 'sang'], 0, 'Cấu trúc chủ động “make + somebody + V nguyên mẫu” không dùng “to”.'),
      q(18, 'My parents let me ___ the school music club.', ['join', 'to join', 'joining', 'joined'], 0, '“Let + somebody + V nguyên mẫu” nghĩa là cho phép ai làm gì.'),
      q(19, 'She decided ___ a piano course.', ['to take', 'take', 'taking', 'took'], 0, '“Decide + to V” = quyết định làm việc gì.'),
      q(20, 'You should ___ the volume down.', ['turn', 'to turn', 'turning', 'turned'], 0, 'Sau động từ khuyết thiếu “should” dùng động từ nguyên mẫu không “to”.'),
      q(21, 'Choose the word with a different stress pattern.', ['singer', 'concert', 'music', 'perform'], 3, 'Singer, concert và music nhấn âm đầu; perform nhấn âm hai.'),
      q(22, 'Choose the word with a different stress pattern.', ['artist', 'album', 'guitar', 'talent'], 2, 'Artist, album và talent nhấn âm đầu; guitar nhấn âm hai.'),
      q(23, 'Choose the word with a different stress pattern.', ['release', 'compose', 'enjoy', 'lyrics'], 3, 'Release, compose và enjoy là các từ nhấn âm hai; lyrics nhấn âm đầu.'),
      q(24, 'Which word has stress on the second syllable?', ['rhythm', 'contest', 'concert', 'success'], 3, '“Success” /səkˈses/ nhấn âm hai; các danh từ còn lại nhấn âm đầu.'),
      q(25, 'Which word has stress on the first syllable?', ['perform', 'decide', 'audience', 'release'], 2, '“Audience” /ˈɔːdiəns/ nhấn âm đầu; perform, decide và release nhấn âm hai.'),
    ],
  },
  {
    id: 4,
    menuLabel: 'Unit 4 · For a Better Community',
    menuGroup: 'unit',
    title: 'Unit 4 · For a Better Community',
    theme: 'Community work · Adjective suffixes · Past tenses · Word stress',
    sourceNote: 'Bài được biên soạn mới theo các chủ điểm công khai của Unit 4: phát triển cộng đồng, tính từ -ing/-ed và -ful/-less, quá khứ đơn–quá khứ tiếp diễn với when/while và trọng âm từ hai âm tiết.',
    passageTitle: '', passage: '',
    reviewNotes: [
      { title: '-ing và -ed', rule: 'Tính từ -ing mô tả sự vật gây cảm xúc; tính từ -ed mô tả cảm xúc của người.', example: 'The job is rewarding. We feel rewarded.' },
      { title: '-ful và -less', rule: '-ful mang nghĩa có/đầy; -less mang nghĩa không có/thiếu.', example: 'helpful · homeless' },
      { title: 'When và while', rule: 'Quá khứ tiếp diễn mô tả việc đang xảy ra; quá khứ đơn mô tả sự việc xen vào. While thường đi với hành động kéo dài.', example: 'While we were cleaning, it started to rain.' },
    ],
    questions: [
      q(1, 'Students collected warm clothes for ___ families.', ['disadvantaged', 'talented', 'confident', 'wealthy'], 0, '“Disadvantaged families” là các gia đình có hoàn cảnh khó khăn.'),
      q(2, 'A person who works without pay to help others is a ___.', ['volunteer', 'donor', 'judge', 'composer'], 0, '“Volunteer” là tình nguyện viên — người tự nguyện đóng góp thời gian và công sức.'),
      q(3, 'The charity received a generous ___.', ['donation', 'development', 'performance', 'instruction'], 0, '“Donation” là khoản quyên góp cho một tổ chức hoặc mục đích.'),
      q(4, 'Our class will ___ money for the local shelter.', ['raise', 'rise', 'take', 'grow'], 0, '“Raise money” nghĩa là gây quỹ; “rise” là tự tăng lên và không có tân ngữ.'),
      q(5, 'The programme provides food and ___ for homeless people.', ['shelter', 'talent', 'lyrics', 'device'], 0, '“Shelter” là nơi trú ẩn — nhu cầu thiết yếu của người vô gia cư.'),
      q(6, 'Community service can make a positive ___.', ['difference', 'different', 'differently', 'differ'], 0, 'Cụm cố định “make a difference” nghĩa là tạo ra thay đổi tích cực.'),
      q(7, 'The volunteers planted trees in a ___ area.', ['public', 'harmful', 'careless', 'privately'], 0, '“Public area” là khu vực công cộng, phù hợp cho hoạt động vì cộng đồng.'),
      q(8, 'They organised a food ___ for families in need.', ['drive', 'record', 'stage', 'footprint'], 0, '“Food drive” là chiến dịch thu gom thực phẩm để quyên góp.'),
      q(9, 'Cleaning the beach was tiring but very ___.', ['rewarding', 'rewarded', 'rewardless', 'reward'], 0, 'Công việc mang lại cảm giác có ý nghĩa nên dùng tính từ gây cảm xúc “rewarding”.'),
      q(10, 'We were ___ by the volunteers’ kindness.', ['inspired', 'inspiring', 'inspire', 'inspiration'], 0, 'Người cảm nhận cảm xúc dùng tính từ -ed: “were inspired”.'),
      q(11, 'The instructions were confusing, so some students felt ___.', ['confused', 'confusing', 'confuse', 'confusion'], 0, 'Instructions gây bối rối là confusing; học sinh cảm thấy bối rối là confused.'),
      q(12, 'Thank you for your ___ advice.', ['helpful', 'helpless', 'helping', 'helped'], 0, '“Helpful advice” là lời khuyên hữu ích; hậu tố -ful mang nghĩa “có tác dụng giúp đỡ”.'),
      q(13, 'The charity supports ___ people during winter.', ['homeless', 'homeful', 'homing', 'homed'], 0, '“Homeless” nghĩa là không có nhà ở; hậu tố -less mang nghĩa thiếu/không có.'),
      q(14, 'Be ___ when carrying these boxes.', ['careful', 'careless', 'caring', 'cared'], 0, '“Be careful” là hãy cẩn thận. Careless mang nghĩa bất cẩn, trái với yêu cầu an toàn.'),
      q(15, 'We ___ litter when the rain started.', ['were collecting', 'collected', 'are collecting', 'collect'], 0, 'Hành động thu gom đang diễn ra thì mưa bắt đầu, nên dùng quá khứ tiếp diễn.'),
      q(16, 'While Lan ___ food, Minh packed the boxes.', ['was preparing', 'prepared', 'is preparing', 'prepares'], 0, '“While” nhấn mạnh hành động kéo dài đang xảy ra: was preparing.'),
      q(17, 'The lights went out while we ___ the charity event.', ['were organising', 'organised', 'organise', 'are organising'], 0, 'Sự kiện mất điện xen vào khi việc tổ chức đang diễn ra, nên dùng were organising.'),
      q(18, 'When the bus ___, the volunteers were waiting outside.', ['arrived', 'was arriving', 'arrives', 'has arrived'], 0, 'Hành động ngắn “bus arrived” xen vào bối cảnh đang chờ, nên dùng quá khứ đơn.'),
      q(19, 'I ___ an elderly neighbour yesterday.', ['helped', 'was helping always', 'help', 'have help'], 0, '“Yesterday” là thời điểm quá khứ đã kết thúc nên dùng quá khứ đơn “helped”.'),
      q(20, 'What ___ you doing when I called?', ['were', 'did', 'was', 'are'], 0, 'Câu hỏi quá khứ tiếp diễn với “you”: What were you doing...?'),
      q(21, 'Which word is stressed on the first syllable?', ['record (noun)', 'record (verb)', 'present (verb)', 'donate'], 0, 'Danh từ “record” nhấn âm đầu: /ˈrekɔːd/; động từ record nhấn âm hai.'),
      q(22, 'Which word is stressed on the second syllable?', ['present (noun)', 'object (noun)', 'increase (verb)', 'project (noun)'], 2, 'Động từ “increase” nhấn âm hai; các danh từ hai âm tiết còn lại thường nhấn âm đầu.'),
      q(23, 'Choose the word with a different stress pattern.', ['volunteer', 'engineer', 'refugee', 'shelter'], 3, 'Volunteer, engineer và refugee nhấn âm cuối; shelter nhấn âm đầu.'),
      q(24, 'The noun “present” is pronounced with stress on the ___.', ['first syllable', 'second syllable', 'both syllables equally', 'final sound'], 0, 'Danh từ “present” /ˈprezənt/ nhấn âm đầu; động từ present /prɪˈzent/ nhấn âm hai.'),
      q(25, 'The verb “record” is pronounced with stress on the ___.', ['second syllable', 'first syllable', 'both syllables equally', 'letter r'], 0, 'Động từ “record” /rɪˈkɔːd/ nhấn âm hai, khác với danh từ “record”.'),
    ],
  },
  {
    id: 5,
    menuLabel: 'Unit 5 · Inventions',
    menuGroup: 'unit',
    title: 'Unit 5 · Inventions',
    theme: 'Technology · Present perfect · V-ing and to-infinitive · Noun stress',
    sourceNote: 'Bài được biên soạn mới theo các chủ điểm công khai của Unit 5: phát minh, hiện tại hoàn thành, V-ing/to V và trọng âm danh từ ba âm tiết.',
    passageTitle: '', passage: '',
    reviewNotes: [
      { title: 'Hiện tại hoàn thành', rule: 'Have/has + V3/ed diễn tả trải nghiệm, kết quả hiện tại hoặc hành động bắt đầu trong quá khứ và còn tiếp tục. Thường đi với since, for, already, yet, ever, never.', example: 'She has used this app for two years.' },
      { title: 'V-ing và to V', rule: 'Enjoy, avoid, finish đi với V-ing; want, decide, hope đi với to V. Remember/stop có thể đổi nghĩa tùy cấu trúc.', example: 'I enjoy using it. / I decided to buy it.' },
      { title: 'Trọng âm danh từ', rule: 'Danh từ ba âm tiết có nhiều mẫu khác nhau; học kèm phiên âm và đánh dấu âm nhấn.', example: 'IN-stru-ment · com-PU-ter' },
    ],
    questions: [
      q(1, 'A smartphone is a useful electronic ___.', ['device', 'inventioner', 'ingredient', 'audience'], 0, '“Electronic device” là thiết bị điện tử như điện thoại, máy tính bảng hoặc máy tính.'),
      q(2, 'The washing machine saves time and ___.', ['effort', 'pollution', 'lyrics', 'shelter'], 0, 'Cụm “save time and effort” nghĩa là tiết kiệm thời gian và công sức.'),
      q(3, 'This app is easy to use because it is ___.', ['user-friendly', 'single-use', 'homeless', 'time-consuming'], 0, '“User-friendly” mô tả sản phẩm thân thiện, dễ sử dụng.'),
      q(4, 'The robot can perform repetitive ___.', ['tasks', 'audiences', 'donations', 'melodies'], 0, 'Robot thường thực hiện các “repetitive tasks” — nhiệm vụ lặp đi lặp lại.'),
      q(5, 'A laptop is more ___ than a desktop computer.', ['portable', 'harmful', 'generous', 'polluted'], 0, '“Portable” nghĩa là dễ mang theo, là ưu điểm của laptop.'),
      q(6, 'The device is powered by a rechargeable ___.', ['battery', 'screen', 'button', 'application'], 0, 'Pin có thể sạc lại là “rechargeable battery”.'),
      q(7, 'The new software will ___ the way students learn.', ['improve', 'inventor', 'operation', 'portable'], 0, 'Sau “will” cần động từ; “improve” nghĩa là cải thiện.'),
      q(8, 'Who was the ___ of this practical machine?', ['inventor', 'invention', 'inventive', 'invent'], 0, 'Cần danh từ chỉ người sau “the”: inventor = nhà phát minh.'),
      q(9, 'I ___ this tablet for three years.', ['have used', 'used', 'am using', 'use'], 0, '“For three years” diễn tả khoảng thời gian kéo dài tới hiện tại, nên dùng hiện tại hoàn thành.'),
      q(10, 'She ___ the software update yet.', ['has not installed', 'did not install', 'does not install', 'is not installing'], 0, '“Yet” trong câu phủ định thường đi với hiện tại hoàn thành: has not + V3.'),
      q(11, '___ you ever ___ a 3D printer?', ['Have / used', 'Did / used', 'Are / using', 'Do / use'], 0, 'Hỏi trải nghiệm tới hiện tại dùng “Have you ever + V3?”'),
      q(12, 'The company has ___ released its newest device.', ['already', 'last week', 'yesterday', 'ago'], 0, '“Already” thường dùng với hiện tại hoàn thành để nói việc đã xảy ra sớm hơn dự kiến.'),
      q(13, 'My brother ___ his phone yesterday.', ['lost', 'has lost yesterday', 'loses', 'has lose'], 0, '“Yesterday” là thời điểm quá khứ xác định, nên dùng quá khứ đơn “lost”.'),
      q(14, 'We have lived here ___ 2022.', ['since', 'for', 'already', 'yet'], 0, '“Since” đi với mốc bắt đầu; 2022 là một mốc thời gian.'),
      q(15, 'How long ___ she ___ this fitness tracker?', ['has / had', 'did / had', 'is / having', 'does / has'], 0, '“How long” hỏi khoảng thời gian kéo dài tới hiện tại: has + subject + V3.'),
      q(16, 'I enjoy ___ new educational apps.', ['trying', 'to trying', 'try', 'tried'], 0, '“Enjoy + V-ing” nên dùng “trying”.'),
      q(17, 'He decided ___ a smart watch.', ['to buy', 'buying', 'buy', 'bought'], 0, '“Decide + to V” nên dùng “to buy”.'),
      q(18, 'Please avoid ___ your phone while crossing the road.', ['using', 'to use', 'use', 'used'], 0, '“Avoid + V-ing” = tránh làm việc gì.'),
      q(19, 'Remember ___ the charger before you leave.', ['to pack', 'packing', 'pack', 'packed'], 0, '“Remember to V” là nhớ phải làm một việc chưa xảy ra.'),
      q(20, 'The technician finished ___ the machine.', ['repairing', 'to repair', 'repair', 'repaired'], 0, '“Finish + V-ing” nên dùng “repairing”.'),
      q(21, 'Choose the noun with stress on the first syllable.', ['instrument', 'computer', 'invention', 'appliance'], 0, '“Instrument” /ˈɪnstrəmənt/ nhấn âm đầu; các từ còn lại nhấn âm sau.'),
      q(22, 'Choose the word with a different stress pattern.', ['computer', 'appliance', 'invention', 'telephone'], 3, 'Computer, appliance và invention nhấn âm hai; telephone nhấn âm đầu.'),
      q(23, 'Which word has stress on the second syllable?', ['digital', 'battery', 'computer', 'camera'], 2, '“Computer” /kəmˈpjuːtə/ nhấn âm hai; digital, battery và camera nhấn âm đầu.'),
      q(24, 'Choose the word with a different stress pattern.', ['energy', 'memory', 'benefit', 'machine'], 3, 'Energy, memory và benefit nhấn âm đầu; machine nhấn âm hai.'),
      q(25, 'Which word is stressed on the first syllable?', ['invention', 'technology', 'device', 'internet'], 3, '“Internet” /ˈɪntənet/ nhấn âm đầu; invention, technology và device đều nhấn ở âm tiết sau.'),
    ],
  },
  {
    id: 6,
    menuLabel: 'Unit 6 · Gender Equality',
    menuGroup: 'unit',
    title: 'Unit 6 · Gender Equality',
    theme: 'Equal opportunities · Modal passive · Adjective and adverb stress',
    sourceNote: 'Bài được biên soạn mới theo các chủ điểm công khai của Unit 6: bình đẳng giới, câu bị động với động từ khuyết thiếu và trọng âm tính từ/trạng từ ba âm tiết.',
    passageTitle: '', passage: '',
    reviewNotes: [
      { title: 'Bị động với động từ khuyết thiếu', rule: 'S + modal + be + V3/ed. Modal có thể là can, should, must, may, will...', example: 'Equal opportunities should be provided.' },
      { title: 'Từ vựng bình đẳng', rule: 'Học theo cụm: equal opportunities, gender discrimination, domestic violence, leadership positions.', example: 'Women should have equal opportunities at work.' },
      { title: 'Trọng âm', rule: 'Đánh dấu trọng âm khi học tính từ và trạng từ ba âm tiết; hậu tố có thể ảnh hưởng vị trí nhấn.', example: 'EQual · eQUAlity · eQUAlly' },
    ],
    questions: [
      q(1, 'All students deserve equal ___.', ['opportunities', 'discrimination', 'violence', 'barriers'], 0, '“Equal opportunities” là cơ hội bình đẳng, không phụ thuộc giới tính.'),
      q(2, 'Treating someone unfairly because of gender is gender ___.', ['discrimination', 'education', 'development', 'participation'], 0, '“Gender discrimination” là phân biệt đối xử dựa trên giới.'),
      q(3, 'The campaign aims to remove barriers to women’s ___.', ['education', 'housework', 'instrument', 'pollution'], 0, 'Cụm phù hợp là loại bỏ rào cản đối với việc học tập của phụ nữ.'),
      q(4, 'Both men and women can hold ___ positions.', ['leadership', 'household', 'recycled', 'musical'], 0, '“Leadership positions” là các vị trí lãnh đạo.'),
      q(5, 'Women make an important ___ to the economy.', ['contribution', 'discrimination', 'inequality', 'barrier'], 0, '“Make a contribution to” nghĩa là đóng góp cho.'),
      q(6, 'Girls should be encouraged to pursue their career ___.', ['choices', 'chores', 'stereotypes', 'violence'], 0, '“Career choices” là những lựa chọn nghề nghiệp.'),
      q(7, 'A fixed and oversimplified belief about a group is a ___.', ['stereotype', 'benefit', 'solution', 'responsibility'], 0, '“Stereotype” là định kiến/khuôn mẫu đơn giản hóa về một nhóm người.'),
      q(8, 'The law protects people from domestic ___.', ['violence', 'equality', 'opportunity', 'education'], 0, '“Domestic violence” là bạo lực gia đình.'),
      q(9, 'Men and women should receive equal ___ for equal work.', ['pay', 'role', 'voice', 'task'], 0, '“Equal pay for equal work” là trả công ngang nhau cho công việc ngang nhau.'),
      q(10, 'Schools can challenge traditional gender ___.', ['roles', 'devices', 'habitats', 'albums'], 0, '“Gender roles” là các vai trò xã hội thường được gắn với giới.'),
      q(11, 'Equal opportunities ___ provided to every student.', ['should be', 'should', 'should being', 'should to be'], 0, 'Bị động với should: should + be + V3 “provided”.'),
      q(12, 'Gender discrimination ___ eliminated.', ['must be', 'must', 'must being', 'must to be'], 0, 'Cấu trúc bị động bắt buộc: must + be + V3.'),
      q(13, 'More leadership programmes ___ created for young women.', ['can be', 'can', 'can being', 'are can'], 0, 'Bị động với can: can be created.'),
      q(14, 'Domestic violence ___ reported to the authorities.', ['should be', 'should', 'is should', 'should being'], 0, 'Chủ ngữ nhận hành động báo cáo nên dùng should be reported.'),
      q(15, 'The same salary ___ paid for the same work.', ['must be', 'must pay', 'must being', 'is must'], 0, '“Salary” được trả, nên dùng bị động “must be paid”.'),
      q(16, 'These stereotypes ___ challenged through education.', ['can be', 'can challenge', 'can being', 'are can be'], 0, 'Các định kiến là đối tượng bị thách thức, nên dùng “can be challenged”.'),
      q(17, 'Nobody should ___ because of their gender.', ['be judged', 'judge', 'be judging', 'judged'], 0, 'Nobody nhận hành động đánh giá: should + be + V3.'),
      q(18, 'The rule may ___ next year.', ['be changed', 'change by', 'be changing by', 'changed'], 0, 'Bị động với may: may be changed.'),
      q(19, 'Women’s achievements should ___ in textbooks.', ['be recognised', 'recognise', 'be recognising', 'recognised'], 0, 'Achievements được công nhận, nên dùng “should be recognised”.'),
      q(20, 'Which sentence is active?', ['Schools must provide equal access.', 'Equal access must be provided.', 'The policy should be changed.', 'Girls can be encouraged.'], 0, 'Câu A có chủ ngữ “Schools” trực tiếp thực hiện hành động “provide”; các câu còn lại là bị động.'),
      q(21, 'Choose the word with a different stress pattern.', ['confident', 'excellent', 'different', 'important'], 3, 'Confident, excellent và different nhấn âm đầu; important nhấn âm hai.'),
      q(22, 'Choose the word with a different stress pattern.', ['equally', 'properly', 'carefully', 'effective'], 3, 'Equally, properly và carefully nhấn âm đầu; effective nhấn âm hai.'),
      q(23, 'Which word has stress on the second syllable?', ['positive', 'excellent', 'important', 'confident'], 2, '“Important” /ɪmˈpɔːtənt/ nhấn âm hai.'),
      q(24, 'Which adverb is stressed on the first syllable?', ['equally', 'completely', 'correctly', 'effectively'], 0, '“Equally” /ˈiːkwəli/ nhấn âm đầu; các từ còn lại nhấn âm sau.'),
      q(25, 'Choose the word with a different stress pattern.', ['successful', 'important', 'effective', 'excellent'], 3, 'Successful, important và effective nhấn âm hai; excellent nhấn âm đầu.'),
    ],
  },
  ...semesterOneExams10,
];
