import type { Exam, Question } from './exams';
import { exam8LanguageBank } from './exams';

type Template = Omit<Question, 'id'>;
type Term = { word: string; meaning: string; example: string };
type Reading = { title: string; passage: string; subject: string; action: string; detail: string; result: string; falseDetail: string };
type UnitSpec = { id: number; title: string; grammar: string; rule: string; example: string; terms: Term[]; reading: Reading };

const soundQuestions: Template[] = [
  { section: 'Language Focus', prompt: 'Choose the word whose underlined ending is pronounced differently.', options: ['washed', 'watched', 'wanted', 'worked'], answer: 2, explanation: 'Đuôi -ed trong “wanted” phát âm /ɪd/ vì động từ kết thúc bằng /t/. Trong washed, watched và worked, -ed phát âm /t/.', underlines: ['ed', 'ed', 'ed', 'ed'] },
  { section: 'Language Focus', prompt: 'Choose the word whose underlined part is pronounced differently.', options: ['school', 'chemistry', 'character', 'chair'], answer: 3, explanation: '“Ch” trong chair phát âm /tʃ/; trong school, chemistry và character, phần “ch” phát âm /k/.', underlines: ['ch', 'ch', 'ch', 'ch'] },
];

const unitSpecs: UnitSpec[] = [
  { id: 7, title: 'Unit 1 · Leisure time', grammar: 'Love/like/hate + V-ing hoặc to V', rule: 'Sau love, like, prefer, hate có thể dùng V-ing hoặc to V. Enjoy, detest và avoid thường đi với V-ing.', example: 'Lan enjoys reading comics and likes to chat with friends.', terms: [
    { word: 'leisure', meaning: 'time when you are free from work or study', example: 'Reading is her favourite leisure activity.' }, { word: 'origami', meaning: 'the art of folding paper into shapes', example: 'Minh makes animals from paper by doing origami.' }, { word: 'hang out', meaning: 'spend relaxed time with friends', example: 'Teenagers often hang out at the sports centre.' }, { word: 'DIY', meaning: 'making or repairing things yourself', example: 'My brother enjoys DIY projects at weekends.' }, { word: 'detest', meaning: 'dislike something very strongly', example: 'She detests waiting for slow websites.' },
  ], reading: { title: 'A balanced free afternoon', passage: 'After school, Thu spends thirty minutes chatting with friends online. She then puts her phone away and practises the guitar. Twice a week, she plays badminton in the park. Thu enjoys technology, but she limits screen time so that her hobbies remain varied.', subject: 'Thu', action: 'balances online and offline leisure activities', detail: 'She practises the guitar after putting her phone away.', result: 'Her leisure time includes both technology and physical activity.', falseDetail: 'She spends the whole afternoon looking at a screen.' } },
  { id: 8, title: 'Unit 2 · Life in the countryside', grammar: 'So sánh hơn của trạng từ', rule: 'Trạng từ ngắn thường thêm -er; trạng từ dài dùng more. Một số dạng bất quy tắc: well → better, badly → worse.', example: 'A horse can run faster than a buffalo.', terms: [
    { word: 'harvest', meaning: 'collect ripe crops from fields', example: 'Farmers harvest rice in autumn.' }, { word: 'orchard', meaning: 'an area where fruit trees are grown', example: 'There is a mango orchard behind the house.' }, { word: 'herd', meaning: 'move and care for a group of animals', example: 'The boy helps his grandfather herd cattle.' }, { word: 'picturesque', meaning: 'visually attractive like a picture', example: 'The village is peaceful and picturesque.' }, { word: 'hospitable', meaning: 'friendly and welcoming to guests', example: 'The local people are very hospitable.' },
  ], reading: { title: 'Morning beside the rice fields', passage: 'Mai’s uncle lives in a small village beside wide rice fields. He wakes early to feed the animals and check the irrigation canal. During harvest time, neighbours work together and share machines. The work is demanding, yet Mai likes the fresh air and strong community spirit.', subject: 'Mai’s uncle and his neighbours', action: 'farm and cooperate in a countryside village', detail: 'Neighbours share machines during the harvest.', result: 'Cooperation helps villagers complete demanding farm work.', falseDetail: 'The village has no fields or animals.' } },
  { id: 9, title: 'Unit 3 · Teenagers', grammar: 'Câu đơn và câu ghép', rule: 'Câu ghép nối hai mệnh đề độc lập bằng and, but, or, so; hoặc dùng trạng từ nối như however, therefore với dấu câu phù hợp.', example: 'I was tired, but I finished my project.', terms: [
    { word: 'pressure', meaning: 'a worried feeling caused by demands', example: 'Too much homework can create pressure.' }, { word: 'bullying', meaning: 'repeated behaviour intended to hurt someone', example: 'Schools need clear rules against bullying.' }, { word: 'forum', meaning: 'an online space for discussion', example: 'Students shared ideas on the class forum.' }, { word: 'deadline', meaning: 'the latest time when work must be finished', example: 'The project deadline is Friday.' }, { word: 'concentrate', meaning: 'give full attention to something', example: 'A quiet room helps me concentrate.' },
  ], reading: { title: 'The peer support corner', passage: 'A secondary school opened a peer support corner during lunch. Trained students listen to classmates who feel stressed or lonely, but they do not replace professional counsellors. If a problem is serious, they help the student contact an adult. The service has made asking for help feel more normal.', subject: 'trained student supporters', action: 'listen to classmates and guide them towards help', detail: 'Serious problems are referred to an adult.', result: 'More teenagers feel comfortable asking for support.', falseDetail: 'Student supporters deal with every serious problem alone.' } },
  { id: 10, title: 'Unit 4 · Ethnic groups of Viet Nam', grammar: 'Câu hỏi Yes/No và Wh-', rule: 'Yes/No questions đặt trợ động từ trước chủ ngữ. Wh-questions bắt đầu bằng who, what, where, when, why hoặc how rồi theo trật tự câu hỏi.', example: 'Where do the Tay live? Do they have traditional festivals?', terms: [
    { word: 'ethnic group', meaning: 'a community sharing culture and traditions', example: 'Viet Nam is home to 54 ethnic groups.' }, { word: 'stilt house', meaning: 'a house raised above the ground on posts', example: 'The family lives in a wooden stilt house.' }, { word: 'costume', meaning: 'traditional or special clothing', example: 'The dancers wore colourful costumes.' }, { word: 'communal house', meaning: 'a shared building for village activities', example: 'People meet at the communal house.' }, { word: 'folk dance', meaning: 'a traditional dance of a community', example: 'Visitors learned a local folk dance.' },
  ], reading: { title: 'A respectful village visit', passage: 'Class 8A visited a Thai community in the northwest. A local guide explained the design of stilt houses and showed the class a traditional weaving loom. Students asked before taking photographs and listened carefully to the hosts. They learned that respectful curiosity makes cultural visits more meaningful.', subject: 'Class 8A', action: 'learned about Thai culture during a village visit', detail: 'Students requested permission before taking photographs.', result: 'Respect helped the class learn more meaningfully.', falseDetail: 'The students entered homes and took photos without asking.' } },
  { id: 11, title: 'Unit 5 · Our customs and traditions', grammar: 'Mạo từ và trường hợp không dùng mạo từ', rule: 'Dùng a/an với danh từ đếm được số ít chưa xác định; the với đối tượng xác định. Không dùng mạo từ trước tên bữa ăn, ngôn ngữ và danh từ số nhiều mang nghĩa chung.', example: 'We have dinner together, and the dinner on New Year’s Eve is special.', terms: [
    { word: 'custom', meaning: 'an accepted way of behaving in a community', example: 'Taking off shoes is a custom in many homes.' }, { word: 'tradition', meaning: 'a belief or practice passed through generations', example: 'The family keeps a New Year tradition.' }, { word: 'worship', meaning: 'show deep respect to a god or ancestor', example: 'Many families worship their ancestors.' }, { word: 'offering', meaning: 'something presented as a sign of respect', example: 'Fruit was placed on the altar as an offering.' }, { word: 'table manners', meaning: 'rules for polite behaviour while eating', example: 'Children learn table manners from adults.' },
  ], reading: { title: 'A meal with meaning', passage: 'On the first morning of Tet, Nam’s family gathers at his grandparents’ home. Before eating, the adults prepare fruit and flowers for the family altar. Children greet older relatives politely and receive good wishes. Nam values the meal because it connects everyday family life with respect for earlier generations.', subject: 'Nam’s family', action: 'follows family customs on the first day of Tet', detail: 'Fruit and flowers are prepared for the altar.', result: 'The celebration connects family members with earlier generations.', falseDetail: 'The children ignore their older relatives.' } },
  { id: 12, title: 'Unit 6 · Lifestyles', grammar: 'Tương lai đơn và điều kiện loại 1', rule: 'Dùng will + V cho dự đoán/quyết định tương lai. Điều kiện loại 1: If + hiện tại đơn, will/can/may + V.', example: 'If people cycle more, the town will become cleaner.', terms: [
    { word: 'lifestyle', meaning: 'the way a person or group lives', example: 'Regular exercise is part of a healthy lifestyle.' }, { word: 'online learning', meaning: 'education delivered through the Internet', example: 'Online learning gives students more flexibility.' }, { word: 'street food', meaning: 'food prepared and sold in public places', example: 'The city is famous for its street food.' }, { word: 'habit', meaning: 'something done regularly, often automatically', example: 'Walking after dinner is a useful habit.' }, { word: 'generation', meaning: 'people born at around the same period', example: 'Each generation uses technology differently.' },
  ], reading: { title: 'One week without a motorbike', passage: 'For a school challenge, Phuc’s family avoided using their motorbike for short journeys. They walked to nearby shops and cycled to the park. At first, planning took longer, but everyone became more active. They decided that if the weather is fine, they will continue cycling at weekends.', subject: 'Phuc’s family', action: 'changed short journeys for one week', detail: 'They walked to nearby shops.', result: 'Family members became more physically active.', falseDetail: 'They used the motorbike for every short journey.' } },
  { id: 13, title: 'Unit 7 · Environmental protection', grammar: 'Mệnh đề trạng từ chỉ thời gian', rule: 'Dùng when, while, before, after, as soon as, until để nối sự việc theo thời gian. Trong mệnh đề thời gian chỉ tương lai, dùng hiện tại đơn thay vì will.', example: 'We will sort the rubbish before we take it outside.', terms: [
    { word: 'habitat', meaning: 'the natural home of an animal or plant', example: 'Wetlands are important bird habitats.' }, { word: 'endangered', meaning: 'at serious risk of disappearing', example: 'The turtle is an endangered species.' }, { word: 'biodiversity', meaning: 'the variety of living things in an area', example: 'Forests contain rich biodiversity.' }, { word: 'contaminate', meaning: 'make something dirty or unsafe', example: 'Chemicals can contaminate groundwater.' }, { word: 'conservation', meaning: 'protection of nature and resources', example: 'The club supports forest conservation.' },
  ], reading: { title: 'Lights out for young turtles', passage: 'A coastal town asks hotels to reduce bright lights during turtle nesting season. When baby turtles leave their nests, they normally move towards light reflected from the sea. Artificial lights can confuse them. Volunteers also clean the beach before the young turtles appear.', subject: 'hotels and volunteers in a coastal town', action: 'protect young turtles during nesting season', detail: 'Bright artificial light can confuse baby turtles.', result: 'Cleaner, darker beaches give young turtles a safer route to the sea.', falseDetail: 'Volunteers add brighter lights beside every nest.' } },
  { id: 14, title: 'Unit 8 · Shopping', grammar: 'Trạng từ tần suất và hiện tại đơn chỉ tương lai', rule: 'Always, usually, often, sometimes, rarely, never đứng trước động từ thường và sau be. Hiện tại đơn dùng cho lịch trình cố định trong tương lai.', example: 'The shop usually opens at nine. The sale starts tomorrow.', terms: [
    { word: 'bargain', meaning: 'something sold for less than its usual value', example: 'This warm jacket was a real bargain.' }, { word: 'customer', meaning: 'a person who buys goods or services', example: 'The assistant greeted every customer.' }, { word: 'receipt', meaning: 'a document proving that payment was made', example: 'Keep the receipt in case you return the item.' }, { word: 'discount', meaning: 'a reduction in the usual price', example: 'Students receive a ten-percent discount.' }, { word: 'browse', meaning: 'look through products without a fixed choice', example: 'We browsed the bookshop for an hour.' },
  ], reading: { title: 'The school swap shop', passage: 'Every final Friday, students bring clean books, uniforms and sports equipment to a swap shop. Each accepted item earns a token that can be exchanged for another item. Teachers check quality, but no money is used. The shop helps families save money and prevents useful goods from being thrown away.', subject: 'students and teachers', action: 'run a monthly school swap shop', detail: 'An accepted item earns one exchange token.', result: 'Families save money and fewer useful items become waste.', falseDetail: 'Students must pay cash for every exchanged item.' } },
  { id: 15, title: 'Unit 9 · Natural disasters', grammar: 'Thì quá khứ tiếp diễn', rule: 'Was/were + V-ing diễn tả hành động đang diễn ra tại một thời điểm quá khứ hoặc khi hành động khác xen vào.', example: 'We were having dinner when the storm warning arrived.', terms: [
    { word: 'earthquake', meaning: 'a sudden shaking of the ground', example: 'The earthquake damaged several roads.' }, { word: 'landslide', meaning: 'a mass of earth and rock moving down a slope', example: 'Heavy rain caused a landslide.' }, { word: 'evacuate', meaning: 'move people away from danger', example: 'Officials evacuated the riverside village.' }, { word: 'emergency kit', meaning: 'essential supplies prepared for a dangerous event', example: 'Our emergency kit contains water and a torch.' }, { word: 'warning', meaning: 'information about possible danger', example: 'Residents received a flood warning.' },
  ], reading: { title: 'A practised response', passage: 'When an earthquake drill began, students were working quietly in class. They moved under strong desks, protected their heads and waited for the signal. After the shaking exercise ended, teachers led them to the playground. Regular practice helped the whole school leave the building calmly.', subject: 'students and teachers', action: 'completed an earthquake safety drill', detail: 'Students protected their heads under strong desks.', result: 'Practice made the evacuation calmer.', falseDetail: 'Everyone ran outside before receiving a signal.' } },
  { id: 16, title: 'Unit 10 · Communication in the future', grammar: 'Giới từ và đại từ sở hữu', rule: 'Dùng at/on/in đúng với thời gian, địa điểm; đại từ sở hữu mine, yours, his, hers, ours, theirs đứng độc lập và không đi trước danh từ.', example: 'The meeting is at eight. This headset is mine.', terms: [
    { word: 'video conference', meaning: 'an online meeting with sound and images', example: 'The class joined a video conference.' }, { word: 'hologram', meaning: 'a three-dimensional image made with light', example: 'The speaker appeared as a hologram.' }, { word: 'telepathy', meaning: 'communication of thoughts without speaking', example: 'Telepathy remains a popular science-fiction idea.' }, { word: 'emoji', meaning: 'a small digital image expressing an idea or feeling', example: 'She added a smiling emoji to the message.' }, { word: 'face-to-face', meaning: 'in direct physical presence', example: 'Some discussions work better face-to-face.' },
  ], reading: { title: 'A classroom across three countries', passage: 'Students in Viet Nam, Japan and Australia meet online once a month. They use live captions when accents are difficult and share digital boards during group work. Technology makes the meetings possible, but teachers also allow quiet thinking time. Students say the project has improved both communication and patience.', subject: 'students in three countries', action: 'collaborate through monthly online meetings', detail: 'Live captions help when accents are difficult.', result: 'Students improve communication and patience.', falseDetail: 'The project completely removes the need to listen carefully.' } },
  { id: 17, title: 'Unit 11 · Science and technology', grammar: 'Câu tường thuật', rule: 'Khi động từ tường thuật ở quá khứ, thường lùi thì: am/is → was, are → were, will → would, can → could; đổi đại từ và trạng từ thời gian khi cần.', example: 'Lan said, “I can help.” → Lan said that she could help.', terms: [
    { word: 'invention', meaning: 'a newly created device or process', example: 'The invention saves water in gardens.' }, { word: 'laboratory', meaning: 'a place equipped for scientific work', example: 'Scientists tested the material in a laboratory.' }, { word: 'digital', meaning: 'using electronic computer technology', example: 'The museum has a digital guide.' }, { word: 'experiment', meaning: 'a scientific test used to discover something', example: 'The class conducted a simple experiment.' }, { word: 'robotic', meaning: 'connected with robots', example: 'A robotic arm lifted the object.' },
  ], reading: { title: 'A sensor for thirsty plants', passage: 'Three pupils built a soil sensor for the school garden. It measures moisture and sends a message when plants need water. During testing, the pupils discovered that one part was not waterproof, so they redesigned its case. Their improved model now helps the gardening club avoid unnecessary watering.', subject: 'three pupils', action: 'designed and improved a soil-moisture sensor', detail: 'Testing revealed that one part was not waterproof.', result: 'The gardening club uses less unnecessary water.', falseDetail: 'The first model worked perfectly and needed no changes.' } },
  { id: 18, title: 'Unit 12 · Life on other planets', grammar: 'Câu tường thuật với câu hỏi', rule: 'Câu hỏi Yes/No tường thuật dùng ask + if/whether; câu hỏi Wh- giữ từ để hỏi. Sau đó dùng trật tự khẳng định, không đảo trợ động từ.', example: 'He asked, “Is Mars cold?” → He asked whether Mars was cold.', terms: [
    { word: 'galaxy', meaning: 'a huge group of stars and planets', example: 'Earth is in the Milky Way galaxy.' }, { word: 'habitable', meaning: 'suitable for living in', example: 'Scientists search for habitable planets.' }, { word: 'gravity', meaning: 'the force that pulls objects towards a planet', example: 'Gravity is weaker on the Moon.' }, { word: 'spacecraft', meaning: 'a vehicle designed to travel in space', example: 'The spacecraft sent images to Earth.' }, { word: 'alien', meaning: 'a possible living being from another world', example: 'The story describes a friendly alien.' },
  ], reading: { title: 'Growing food far from Earth', passage: 'Scientists are studying how plants might grow during long space journeys. In a closed chamber, they control light, water and temperature while measuring each plant. Growing fresh food could support astronauts and improve their mood. However, every drop of water must be reused because supplies are limited.', subject: 'scientists studying space agriculture', action: 'test plant growth in a controlled chamber', detail: 'Light, water and temperature are carefully controlled.', result: 'Fresh plants could provide food and emotional benefits.', falseDetail: 'Water supplies in space are unlimited.' } },
];

const makeVocabulary = (terms: Term[]): Template[] => terms.map((term, index) => {
  const alternatives = terms.filter((_, itemIndex) => itemIndex !== index).map((item) => item.word).slice(0, 3);
  const answer = index % 4;
  const options = [...alternatives];
  options.splice(answer, 0, term.word);
  return { section: 'Language Focus', prompt: `Which word or phrase means “${term.meaning}”?`, options, answer, explanation: `“${term.word}” có nghĩa là ${term.meaning}. Ví dụ: ${term.example}` };
});

const readingQuestions = (reading: Reading): Template[] => [
  { section: 'Reading', prompt: `What is “${reading.title}” mainly about?`, options: [reading.action, reading.falseDetail, 'A commercial advertisement', 'An unrelated competition'], answer: 0, explanation: `Ý chính của bài là việc ${reading.action.toLowerCase()}; các phương án khác trái với nội dung hoặc không bao quát toàn bài.` },
  { section: 'Reading', prompt: `Who is the main subject of “${reading.title}”?`, options: [reading.subject, 'international reporters', 'professional athletes', 'factory owners'], answer: 0, explanation: `Chủ thể chính được bài đọc nhắc xuyên suốt là ${reading.subject}.` },
  { section: 'Reading', prompt: 'Which detail is stated in the passage?', options: [reading.detail, reading.falseDetail, 'The activity was cancelled.', 'Nobody learned anything.'], answer: 0, explanation: `Bài đọc nêu trực tiếp: “${reading.detail}” Các lựa chọn khác không được xác nhận.` },
  { section: 'Reading', prompt: reading.result, options: ['True', 'False'], answer: 0, explanation: `TRUE. Bài đọc xác nhận kết quả này: ${reading.result}` },
  { section: 'Reading', prompt: reading.falseDetail, options: ['True', 'False'], answer: 1, explanation: 'FALSE. Nhận định trái với thông tin trong bài; hãy tìm câu có cùng từ khóa rồi kiểm tra ý nghĩa thay vì chỉ nhìn từ giống nhau.' },
];

const selectCommon = (offset: number, count: number): Template[] => {
  const chosen: Question[] = [];
  let cursor = offset % exam8LanguageBank.length;
  while (chosen.length < count) {
    const item = exam8LanguageBank[cursor];
    if (!chosen.includes(item)) chosen.push(item);
    cursor = (cursor + 11) % exam8LanguageBank.length;
  }
  return chosen.map(({ id: _id, ...item }) => item);
};

const unitExams: Exam[] = unitSpecs.map((unit, index) => {
  const templates = [...makeVocabulary(unit.terms), ...soundQuestions, ...selectCommon(index * 13, 13), ...readingQuestions(unit.reading)];
  return { id: unit.id, menuLabel: unit.title, menuGroup: 'unit', title: `English 8 · ${unit.title}`, theme: `${unit.grammar} · 25 câu`, sourceNote: 'Nội dung được biên soạn mới theo chủ đề, từ vựng và ngữ pháp công khai của chương trình Tiếng Anh 8 Global Success trên Loigiaihay.', passageTitle: unit.reading.title, passage: unit.reading.passage, reviewNotes: [{ title: unit.grammar, rule: unit.rule, example: unit.example }], questions: templates.map((item, questionIndex) => ({ ...item, id: questionIndex + 1 })) };
});

const semesterReadings: Reading[] = [
  { title: 'A six-unit revision plan', passage: 'Huy divided his first-semester revision into six topic cards. He reviewed one card each day, wrote his own grammar examples and completed a short reading task. At the end of the week, he returned to mistakes instead of repeating questions he already knew. This method made his study time more focused.', subject: 'Huy', action: 'uses a focused six-topic revision plan', detail: 'He writes his own grammar examples.', result: 'Reviewing mistakes makes his study time more useful.', falseDetail: 'He repeats only questions that he already knows.' },
  { title: 'A hobby shared across generations', passage: 'Linh learned basket weaving from her grandmother during the school holiday. At first, she worked slowly and made uneven shapes. Her grandmother encouraged her to practise a little each morning. By the end of the holiday, Linh had finished a useful basket and understood why patience matters in traditional crafts.', subject: 'Linh and her grandmother', action: 'share a traditional craft as a leisure activity', detail: 'Linh practises for a short time each morning.', result: 'Linh improves her skill and learns patience.', falseDetail: 'Linh makes a perfect basket on her first attempt.' },
  { title: 'A teen-designed quiet room', passage: 'Students suggested turning an unused classroom into a quiet room. They added plants, simple chairs and a rule that phones must remain silent. Teenagers can read or rest there for fifteen minutes. Teachers report that many students return to lessons calmer and ready to concentrate.', subject: 'students and teachers', action: 'create and use a quiet room at school', detail: 'Phones must remain silent in the room.', result: 'The room helps students return to lessons more calmly.', falseDetail: 'Students use the room for loud online games.' },
  { title: 'Weekend in a highland village', passage: 'During a weekend visit, Nhi stayed with a family in a highland village. She helped feed chickens, watched cloth being woven and joined a folk dance in the communal house. Her hosts explained each activity before she tried it. Nhi left with a deeper respect for a lifestyle different from her own.', subject: 'Nhi and her host family', action: 'share daily life and culture during a village visit', detail: 'Nhi joins a folk dance in the communal house.', result: 'The visit increases Nhi’s respect for another lifestyle.', falseDetail: 'Nhi refuses to learn about local activities.' },
  { title: 'A greener Mid-Autumn Festival', passage: 'A neighbourhood group wanted to reduce waste at its Mid-Autumn Festival. Children made lanterns from used paper, families brought reusable cups and volunteers sorted rubbish after the event. The celebration kept its traditional songs and games while producing much less plastic waste.', subject: 'a neighbourhood group', action: 'combines a traditional festival with waste reduction', detail: 'Children make lanterns from used paper.', result: 'The festival keeps traditions while creating less plastic waste.', falseDetail: 'All traditional songs and games are removed.' },
  { title: 'Different routines, one family', passage: 'Mr Son starts work early, while his teenage daughter studies mainly in the afternoon. They rarely have breakfast together, so the family protects dinner time instead. Everyone puts devices away and shares one event from the day. This small habit helps them stay connected despite different schedules.', subject: 'Mr Son’s family', action: 'uses a shared dinner routine to stay connected', detail: 'Everyone shares one event from the day.', result: 'A simple habit supports family communication.', falseDetail: 'Family members use their devices throughout dinner.' },
  { title: 'Young guides at the local museum', passage: 'A local museum trained secondary students to guide weekend visitors. The students researched objects, practised explaining them clearly and learned to answer respectful questions. Visitors enjoyed hearing young voices, and the students became more confident speaking in public.', subject: 'secondary students at a local museum', action: 'serve as trained weekend museum guides', detail: 'Students research objects before guiding visitors.', result: 'The programme benefits both visitors and student confidence.', falseDetail: 'Students guide visitors without learning about the objects.' },
  { title: 'The repair-and-share morning', passage: 'Once a month, residents bring damaged toys and small household items to the community hall. Volunteers repair what they can and explain simple maintenance. Items that owners no longer need are exchanged. The event saves money, reduces waste and gives neighbours time to talk.', subject: 'residents and repair volunteers', action: 'repair and exchange useful household items', detail: 'Volunteers explain simple maintenance.', result: 'The event reduces waste and strengthens community contact.', falseDetail: 'Every damaged object is immediately thrown away.' },
  { title: 'Learning safely from a flood', passage: 'After a small flood, students interviewed residents about what had helped them stay safe. They mapped higher routes, checked emergency phone numbers and prepared sample supply bags. The class did not treat the event as entertainment; they used local experience to improve a practical school safety plan.', subject: 'students and local residents', action: 'turn flood experience into a school safety plan', detail: 'Students map routes on higher ground.', result: 'Local experience improves practical disaster preparation.', falseDetail: 'The class treats the flood only as entertainment.' },
];

const finalExams: Exam[] = semesterReadings.map((reading, index) => {
  const isReview = index === 0;
  const templates = [...soundQuestions, ...selectCommon(index * 17 + 5, 18), ...readingQuestions(reading)];
  return { id: index + 19, menuLabel: isReview ? 'Ôn tập cuối kỳ I' : `Cuối kỳ I · Đề ${index}`, menuGroup: isReview ? 'review' : 'final', title: isReview ? 'English 8 · Ôn tập cuối kỳ I' : `English 8 · Đề cuối kỳ I số ${index}`, theme: isReview ? 'Tổng ôn Units 1–6 · 25 câu' : 'Units 1–6 · Không gồm phần nghe', sourceNote: 'Bộ câu hỏi được biên soạn lại theo phạm vi và cấu trúc đề học kỳ I Tiếng Anh 8 Global Success trên Loigiaihay; không sao chép nguyên văn và đã loại bỏ phần nghe.', passageTitle: reading.title, passage: reading.passage, reviewNotes: isReview ? unitSpecs.slice(0, 6).map((unit) => ({ title: unit.grammar, rule: unit.rule, example: unit.example })) : undefined, questions: templates.map((item, questionIndex) => ({ ...item, id: questionIndex + 1 })) };
});

export const additionalExams8: Exam[] = [...unitExams, ...finalExams];
