import type { Exam, Question } from './exams';
import { midtermExams9 } from './exams9-midterm';
import { finalExams9 } from './exams9-final';
import { unitExams9 } from './exams9-units';

const q = (
  id: number,
  section: Question['section'],
  prompt: string,
  options: string[],
  answer: number,
  explanation: string,
  underlines?: string[],
): Question => ({ id, section, prompt, options, answer, explanation, underlines });

export const exams9: Exam[] = [
  ...unitExams9,
  {
    id: 1,
    menuLabel: 'Khảo sát đầu năm',
    menuGroup: 'survey',
    title: 'Khảo sát chất lượng đầu năm · Đề số 1',
    theme: 'Ôn nền tảng lớp 8 → 9',
    passageTitle: 'Understanding volcanoes',
    passage:
      'Volcanoes are often grouped into three types. Active volcanoes erupt or show signs that an eruption may happen. Extinct volcanoes have lost their heat source and are not expected to erupt again. Dormant volcanoes have been quiet for a long time, but they may become active in the future. Scientists study volcanoes in several ways. They examine rocks, make maps, measure small movements in the ground, and use satellites to observe changes from space. These methods can provide useful warnings, but predicting the exact time of an eruption is still extremely difficult.',
    questions: [
      q(1, 'Language Focus', 'Choose the word whose underlined part is pronounced differently.', ['thank', 'father', 'theatre', 'healthy'], 1, 'Phần “th” trong “father” được phát âm /ð/ (âm hữu thanh). Trong “thank”, “theatre” và “healthy”, “th” được phát âm /θ/ (âm vô thanh). Vì vậy đáp án B khác ba từ còn lại.', ['th', 'th', 'th', 'th']),
      q(2, 'Language Focus', 'Choose the word with a different stress pattern.', ['suburb', 'neighbour', 'tourist', 'remind'], 3, '“Suburb”, “neighbour” và “tourist” đều nhấn âm tiết thứ nhất. “Remind” /rɪˈmaɪnd/ nhấn âm tiết thứ hai, nên chọn D.'),
      q(3, 'Language Focus', 'My grandparents live ___ a quiet suburb of the city.', ['at', 'in', 'on', 'from'], 1, 'Dùng giới từ “in” trước một khu vực hoặc địa điểm có phạm vi: in a suburb, in a city. Câu có nghĩa: Ông bà tôi sống trong một vùng ngoại ô yên tĩnh của thành phố.'),
      q(4, 'Language Focus', 'Lan could not decide ___ to invite to the science fair.', ['what', 'where', 'who', 'when'], 2, 'Cấu trúc “question word + to-infinitive”. Vì động từ “invite” cần một người làm tân ngữ, ta dùng “who to invite” = mời ai.'),
      q(5, 'Language Focus', 'It is ___ easier to prevent damage than to repair it later.', ['always', 'never', 'rarely', 'hardly'], 0, '“Always” diễn tả một nguyên tắc luôn đúng trong ngữ cảnh: phòng tránh thiệt hại luôn dễ hơn sửa chữa về sau. Các trạng từ phủ định hoặc tần suất thấp làm câu sai nghĩa.'),
      q(6, 'Language Focus', 'I did not fully understand tsunami warnings ___ I watched a documentary about them.', ['while', 'until', 'because', 'although'], 1, 'Mẫu “not ... until” nghĩa là mãi cho đến khi điều gì xảy ra thì trạng thái mới thay đổi. Ở đây: Tôi chưa hiểu đầy đủ cảnh báo sóng thần cho đến khi xem phim tài liệu.'),
      q(7, 'Language Focus', 'Millions of viewers watched the rescue operation ___ on television.', ['lively', 'alive', 'live', 'living'], 2, '“Live” ở đây là trạng từ/tính từ chỉ chương trình được phát trực tiếp. “Alive” nghĩa là còn sống; “lively” là sôi nổi; “living” là đang sống.'),
      q(8, 'Language Focus', 'Scientists may discover another habitable planet ___ the next twenty years.', ['for', 'since', 'in', 'at'], 2, '“In + khoảng thời gian” có thể chỉ một sự việc sẽ xảy ra trong tương lai: in the next twenty years. “For” chỉ độ dài; “since” đi với mốc bắt đầu.'),
      q(9, 'Language Focus', 'Our teacher ___ us to follow the evacuation signs carefully.', ['said', 'spoke', 'told', 'asked to'], 2, 'Cấu trúc “tell somebody to + V”: told us to follow. “Say” không đi trực tiếp với tân ngữ người theo mẫu này; “asked to” còn thiếu tân ngữ đúng vị trí.'),
      q(10, 'Language Focus', '___ bicycle needs to be washed before the trip.', ['Mine', 'My', 'Me', 'I'], 1, 'Trước danh từ “bicycle” cần tính từ sở hữu “my”. “Mine” là đại từ sở hữu nên đứng độc lập, không đứng trước danh từ.'),
      q(11, 'Language Focus', 'The safety report has to ___ before Friday.', ['submit', 'be submitted', 'submitted', 'be submitting'], 1, 'Chủ ngữ “the safety report” nhận hành động, nên dùng bị động sau “has to”: has to be + V3. “Submit” có V3 là “submitted”.'),
      q(12, 'Language Focus', 'Would you mind if I ___ the window?', ['open', 'opened', 'will open', 'am opening'], 1, 'Sau “Would you mind if I ...?” thường dùng quá khứ đơn để đưa ra lời xin phép lịch sự: if I opened. Đây không mang nghĩa quá khứ.'),
      q(13, 'Language Focus', 'Malaysia is made up ___ thirteen states and three federal territories.', ['by', 'from', 'of', 'with'], 2, 'Cụm cố định “be made up of” = bao gồm/được tạo thành từ. Vì vậy dùng “of”.'),
      q(14, 'Language Focus', 'The new bridge ___ built five years ago.', ['is', 'was', 'were', 'has'], 1, '“Five years ago” yêu cầu quá khứ đơn. Chủ ngữ “the new bridge” số ít và câu ở thể bị động, nên dùng “was built”.'),
      q(15, 'Language Focus', 'Nam said that he ___ from a small coastal town.', ['comes', 'came', 'will come', 'has come'], 1, 'Trong lời nói gián tiếp với động từ tường thuật “said” ở quá khứ, hiện tại đơn thường lùi thành quá khứ đơn: come → came.'),
      q(16, 'Language Focus', 'It rained heavily, ___ the outdoor match was cancelled.', ['but', 'because', 'so', 'although'], 2, 'Vế trước là nguyên nhân, vế sau là kết quả; “so” nối hai mệnh đề theo nghĩa “vì vậy”. “Because” sẽ đảo quan hệ và không phù hợp dấu phẩy ở đây.'),
      q(17, 'Language Focus', 'While we ___ home, we saw an accident near the station.', ['walked', 'were walking', 'are walking', 'have walked'], 1, 'Một hành động đang diễn ra thì hành động ngắn xen vào: “were walking” (quá khứ tiếp diễn) đi với “saw” (quá khứ đơn).'),
      q(18, 'Language Focus', 'The storm was severe, ___ nobody in the village was injured.', ['so', 'because', 'but', 'therefore'], 2, 'Hai ý tương phản: bão dữ dội nhưng không ai bị thương. “But” là liên từ thích hợp để nối hai mệnh đề.'),
      q(19, 'Language Focus', 'Could you show me ___ to use this emergency radio?', ['how', 'who', 'which person', 'how do I'], 0, 'Cấu trúc gián tiếp “show somebody how to + V” = chỉ cho ai cách làm gì. Không đảo trợ động từ trong câu hỏi gián tiếp.'),
      q(20, 'Language Focus', 'I wish I ___ more about first aid.', ['know', 'knew', 'will know', 'am knowing'], 1, '“Wish” về một điều không đúng ở hiện tại dùng quá khứ đơn: wish + S + V2. “I wish I knew” nghĩa là tôi ước mình biết nhiều hơn.'),
      q(21, 'Reading', 'An active volcano may erupt or show signs of a possible eruption.', ['True', 'False'], 0, 'TRUE. Câu thứ hai giải thích núi lửa đang hoạt động có thể phun trào hoặc biểu hiện dấu hiệu cho thấy một vụ phun trào có thể xảy ra.'),
      q(22, 'Reading', 'An extinct volcano is expected to erupt again soon.', ['True', 'False'], 1, 'FALSE. Bài đọc nói núi lửa đã tắt mất nguồn nhiệt và không được dự đoán sẽ phun trào trở lại. “Soon” trái hẳn với thông tin trong bài.'),
      q(23, 'Reading', 'A dormant volcano can possibly become active in the future.', ['True', 'False'], 0, 'TRUE. “Dormant” là im lặng trong thời gian dài, nhưng bài nhấn mạnh loại núi lửa này vẫn có thể hoạt động lại trong tương lai.'),
      q(24, 'Reading', 'Scientists observe volcanoes only from the ground.', ['True', 'False'], 1, 'FALSE. Ngoài nghiên cứu đá, lập bản đồ và đo chuyển động mặt đất, các nhà khoa học còn dùng vệ tinh để quan sát thay đổi từ không gian.'),
      q(25, 'Reading', 'Scientists can always predict the exact time of an eruption.', ['True', 'False'], 1, 'FALSE. Câu cuối cho biết dự đoán chính xác thời điểm phun trào vẫn cực kỳ khó. Các phương pháp chỉ cung cấp cảnh báo hữu ích, không bảo đảm chính xác tuyệt đối.'),
    ],
  },
  {
    id: 2,
    menuLabel: 'Ôn tập Unit 1–3',
    menuGroup: 'review',
    title: 'Ôn tập giữa học kỳ I · Unit 1–3',
    theme: 'Local community · City life · Healthy teens',
    sourceNote: 'Bài luyện được chọn lọc và biên soạn lại từ 3 tài liệu VietJack bạn đã gửi: đề giữa kỳ Bắc Ninh, đề cương Unit 1–3 và ngữ pháp Global Success 9.',
    passageTitle: 'A healthier school week',
    passage:
      'At Green Hill School, students have started a programme called “A Healthier School Week”. They walk or cycle to school when possible and bring balanced lunches with fruit and vegetables. After every forty-five minutes of study, they take a short break to stretch and rest their eyes. The school also encourages students to turn off their phones during homework time. On Friday afternoon, local craftspeople visit the school and teach small groups how to make simple products. The programme helps teenagers care for their health while staying connected with their local community.',
    reviewNotes: [
      { title: 'Wh-word + to V', rule: 'Dùng sau know, decide, ask, show, tell… để diễn đạt điều cần làm một cách ngắn gọn. Không dùng “why + to V”.', example: 'I do not know where to buy this pottery.' },
      { title: 'Phrasal verbs', rule: 'Học nghĩa của cả cụm, không dịch từng từ. Với cụm tách được, đại từ thường đứng giữa động từ và tiểu từ.', example: 'Please look the word up. / Please look it up.' },
      { title: 'So sánh kép', rule: 'The + comparative, the + comparative diễn tả hai sự thay đổi liên hệ với nhau.', example: 'The more you practise, the more confident you become.' },
      { title: 'Điều kiện loại 1', rule: 'If + hiện tại đơn, S + will/can/may/must/should + V. Mệnh đề if nêu điều kiện có thể xảy ra.', example: 'If you feel stressed, you should take a short break.' },
      { title: 'Từ vựng Unit 1–3', rule: 'Ôn từ theo cụm: local speciality, carry out a project, public transport, balanced diet, mental health.', example: 'The city is carrying out a project to improve traffic.' },
    ],
    questions: [
      q(1, 'Language Focus', 'Choose the word whose underlined part is pronounced differently.', ['honest', 'homework', 'handmade', 'healthy'], 0, 'Chữ “h” trong “honest” là âm câm, từ bắt đầu bằng nguyên âm /ˈɒnɪst/. Ba từ còn lại đều phát âm /h/ ở đầu. Vì vậy chọn A.', ['h', 'h', 'h', 'h']),
      q(2, 'Language Focus', 'Choose the word whose underlined part is pronounced differently.', ['market', 'card', 'depart', 'scare'], 3, 'Phần “ar” trong market, card và depart có âm /ɑː/. Trong “scare”, phần tương ứng tạo âm /eə/, nên D khác.', ['ar', 'ar', 'ar', 'ar']),
      q(3, 'Language Focus', 'Choose the word whose underlined part is pronounced differently.', ['thread', 'pleasure', 'deadline', 'treat'], 3, '“ea” trong thread, pleasure và deadline được đọc /e/. Trong “treat”, “ea” đọc /iː/, nên chọn D.', ['ea', 'ea', 'ea', 'ea']),
      q(4, 'Language Focus', 'Choose the word with a different stress pattern.', ['village', 'football', 'object', 'invent'], 3, 'Village, football và object (danh từ) nhấn âm đầu. Invent /ɪnˈvent/ nhấn âm thứ hai, nên chọn D.'),
      q(5, 'Language Focus', 'Choose the word with a different stress pattern.', ['suburb', 'neighbour', 'people', 'advice'], 3, 'Suburb, neighbour và people nhấn âm đầu. Advice /ədˈvaɪs/ nhấn âm thứ hai, nên chọn D.'),
      q(6, 'Language Focus', 'The village is famous for a sweet rice cake that is its local ___.', ['speciality', 'facility', 'appliance', 'delivery'], 0, '“Local speciality” là đặc sản địa phương. Facility là cơ sở vật chất; appliance là thiết bị gia dụng; delivery là việc giao hàng.'),
      q(7, 'Language Focus', 'The council is ___ a plan to make the town centre safer.', ['looking after', 'carrying out', 'running out of', 'turning down'], 1, '“Carry out a plan” nghĩa là thực hiện một kế hoạch. Câu đang ở hiện tại tiếp diễn nên dùng “is carrying out”.'),
      q(8, 'Language Focus', 'Living near the metro is convenient because it is a form of ___.', ['public transport', 'housing benefit', 'private space', 'handicraft'], 0, 'Metro là tàu điện ngầm, thuộc hệ thống giao thông công cộng nên “public transport” là đáp án đúng.'),
      q(9, 'Language Focus', 'A balanced diet supports both physical and ___ health.', ['mental', 'downtown', 'crafty', 'electric'], 0, 'Cụm thường dùng là “physical and mental health” = sức khỏe thể chất và tinh thần. Các lựa chọn khác không thể bổ nghĩa phù hợp cho “health”.'),
      q(10, 'Language Focus', 'The restaurant is excellent, but it is rather ___.', ['price', 'priced', 'pricey', 'pricing'], 2, 'Sau “is rather” cần tính từ. “Pricey” là tính từ, nghĩa là khá đắt. “Price” là danh từ/động từ.'),
      q(11, 'Language Focus', 'Mai cannot decide ___ to ask for advice.', ['who', 'why', 'whose does she', 'who does'], 0, 'Cấu trúc đúng là “decide + wh-word + to V”: decide who to ask. Không dùng trợ động từ “does”, và “why + to V” không đúng trong cấu trúc này.'),
      q(12, 'Language Focus', 'Could you show us ___ to get to the community centre?', ['what', 'where', 'how', 'who'], 2, '“How to get to…” diễn tả cách đi đến một nơi. Mẫu câu: show somebody how to + V.'),
      q(13, 'Language Focus', 'We need to cut down ___ single-use plastic.', ['at', 'of', 'on', 'for'], 2, 'Cụm động từ “cut down on” nghĩa là cắt giảm số lượng hoặc mức sử dụng một thứ gì đó.'),
      q(14, 'Language Focus', 'This weaving technique was passed ___ from older artisans.', ['down', 'out', 'away', 'off'], 0, '“Pass down” nghĩa là truyền lại kiến thức, kỹ năng hoặc truyền thống cho thế hệ sau.'),
      q(15, 'Language Focus', 'We have run ___ clean drinking water.', ['out', 'out of', 'away from', 'down on'], 1, '“Run out of + noun” = hết một thứ gì. Vì theo sau là “clean drinking water”, cần đủ cụm “out of”.'),
      q(16, 'Language Focus', 'The more carefully you plan your day, the ___ time you waste.', ['least', 'less', 'little', 'few'], 1, 'So sánh kép: “The more…, the less…”. Time là danh từ không đếm được, nên dùng “less”, không dùng “fewer”.'),
      q(17, 'Language Focus', 'The ___ the bus service becomes, the more people will use it.', ['reliable', 'more reliable', 'most reliable', 'reliably'], 1, 'Mẫu “The + comparative, the + comparative”. Reliable là tính từ dài nên dạng so sánh hơn là “more reliable”.'),
      q(18, 'Language Focus', 'If you feel overwhelmed, you ___ talk to a trusted adult.', ['should', 'should to', 'will to', 'are'], 0, 'Trong câu điều kiện loại 1, mệnh đề chính có thể dùng “should + V” để đưa lời khuyên. Sau should là động từ nguyên mẫu không “to”.'),
      q(19, 'Language Focus', 'If the craft shop closes early, we ___ come back tomorrow.', ['can', 'could to', 'are able', 'can to'], 0, 'Mệnh đề if dùng hiện tại đơn “closes”; mệnh đề chính dùng động từ tình thái “can + V”: can come back.'),
      q(20, 'Language Focus', 'If you want better sleep, you ___ use your phone in bed.', ['should not', 'do not should', 'will not to', 'are not'], 0, 'Lời khuyên phủ định dùng “should not + V”. Câu có nghĩa: Nếu muốn ngủ ngon hơn, bạn không nên dùng điện thoại trên giường.'),
      q(21, 'Reading', 'Students in the programme sometimes walk or cycle to school.', ['True', 'False'], 0, 'TRUE. Bài đọc nói học sinh đi bộ hoặc đi xe đạp đến trường khi điều kiện cho phép.'),
      q(22, 'Reading', 'Their lunches contain only fast food.', ['True', 'False'], 1, 'FALSE. Các em mang bữa trưa cân bằng có trái cây và rau, trái với “only fast food”.'),
      q(23, 'Reading', 'Students take a short break after forty-five minutes of studying.', ['True', 'False'], 0, 'TRUE. Chi tiết này được nêu trực tiếp: sau mỗi 45 phút học, các em nghỉ ngắn để giãn cơ và cho mắt nghỉ.'),
      q(24, 'Reading', 'The school advises students to keep their phones on while doing homework.', ['True', 'False'], 1, 'FALSE. Nhà trường khuyến khích học sinh tắt điện thoại trong thời gian làm bài tập về nhà.'),
      q(25, 'Reading', 'Local craftspeople help students learn simple practical skills.', ['True', 'False'], 0, 'TRUE. Chiều thứ Sáu, thợ thủ công địa phương đến trường và hướng dẫn các nhóm nhỏ làm sản phẩm đơn giản.'),
    ],
  },
  ...midtermExams9,
  ...finalExams9,
];
