import type { Exam, Question } from './exams';
import type { GrammarLesson, GrammarTopic } from './grammar-lessons9';
import type { UnitEnrichment } from './unit-enrichment';
import type { VocabularyItem } from './vocabulary';
import { distributeAnswers, distributeExams } from './answer-distribution';

export type ExtendedGrade = 6 | 7 | 11 | 12;
type Vocab = [word: string, vietnamese: string, definition: string, example: string, partOfSpeech?: string];
type UnitSeed = [title: string, vocabulary: Vocab[]];
type GrammarProfile = GrammarTopic & { correct: string; wrong: [string, string, string] };

const grammarByGrade: Record<ExtendedGrade, GrammarProfile[]> = {
  6: [
    { title: 'Present simple', meaning: 'Diễn tả thói quen, lịch trình và sự thật.', structure: ['S + V(s/es)', 'S + do/does not + V', 'Do/Does + S + V?'], use: 'Dùng với always, usually, often, sometimes, every day.', examples: [{ english: 'Mai walks to school every morning.', vietnamese: 'Mai đi bộ đến trường mỗi sáng.' }], note: 'Với he, she, it, động từ thường thêm -s hoặc -es.', correct: 'Mai walks to school every morning.', wrong: ['Mai walk to school every morning.', 'Mai is walk to school every morning.', 'Mai walking to school every morning.'] },
    { title: 'Present continuous', meaning: 'Diễn tả hành động đang xảy ra hoặc tình huống tạm thời.', structure: ['S + am/is/are + V-ing', 'S + am/is/are not + V-ing', 'Am/Is/Are + S + V-ing?'], use: 'Dùng với now, right now, at the moment, Look! và Listen!', examples: [{ english: 'The children are playing outside now.', vietnamese: 'Bọn trẻ đang chơi bên ngoài.' }], note: 'Không bỏ động từ be trước V-ing.', correct: 'The children are playing outside now.', wrong: ['The children playing outside now.', 'The children is playing outside now.', 'The children play outside now at the moment.'] },
    { title: 'Comparative adjectives', meaning: 'So sánh hai người, vật hoặc nơi.', structure: ['short adjective + -er + than', 'more + long adjective + than', 'good → better; bad → worse'], use: 'Dùng than sau tính từ so sánh hơn.', examples: [{ english: 'This park is quieter than the city centre.', vietnamese: 'Công viên này yên tĩnh hơn trung tâm.' }], note: 'Không dùng đồng thời more và đuôi -er.', correct: 'This park is quieter than the city centre.', wrong: ['This park is more quieter than the city centre.', 'This park is quiet than the city centre.', 'This park quieter the city centre.'] },
    { title: 'Will for future predictions', meaning: 'Đưa ra dự đoán hoặc quyết định tức thời.', structure: ['S + will + V', 'S + will not + V', 'Will + S + V?'], use: 'Sau will dùng động từ nguyên mẫu không to.', examples: [{ english: 'Robots will help people at home.', vietnamese: 'Rô-bốt sẽ giúp con người ở nhà.' }], note: 'Không thêm -s hoặc -ed sau will.', correct: 'Robots will help people at home.', wrong: ['Robots will helps people at home.', 'Robots will to help people at home.', 'Robots helping people at home will.'] },
  ],
  7: [
    { title: 'Verbs of liking + V-ing', meaning: 'Diễn tả sở thích hoặc sự yêu thích hoạt động.', structure: ['like/love/enjoy/prefer + V-ing', 'dislike/hate + V-ing'], use: 'Sau enjoy luôn dùng danh động từ V-ing.', examples: [{ english: 'Lan enjoys collecting postcards.', vietnamese: 'Lan thích sưu tầm bưu thiếp.' }], note: 'Sai: enjoy to collect. Đúng: enjoy collecting.', correct: 'Lan enjoys collecting postcards.', wrong: ['Lan enjoys collect postcards.', 'Lan enjoy collecting postcards.', 'Lan enjoys to collecting postcards.'] },
    { title: 'Past simple', meaning: 'Diễn tả hành động đã hoàn tất trong quá khứ.', structure: ['S + V2/ed', 'S + did not + V', 'Did + S + V?'], use: 'Dùng với yesterday, last week, ago và mốc quá khứ.', examples: [{ english: 'Our class planted trees last Saturday.', vietnamese: 'Lớp chúng tôi trồng cây thứ Bảy trước.' }], note: 'Sau did/did not dùng động từ nguyên mẫu.', correct: 'Our class planted trees last Saturday.', wrong: ['Our class plant trees last Saturday.', 'Our class did planted trees last Saturday.', 'Our class was plant trees last Saturday.'] },
    { title: 'Comparisons with like, different from and as ... as', meaning: 'Nêu sự giống nhau, khác nhau hoặc ngang bằng.', structure: ['A is like B', 'A is different from B', 'A is as + adjective + as B'], use: 'Dùng as ... as cho mức độ bằng nhau.', examples: [{ english: 'This painting is as colourful as that one.', vietnamese: 'Bức tranh này nhiều màu sắc như bức kia.' }], note: 'Không dùng than trong cấu trúc as ... as.', correct: 'This painting is as colourful as that one.', wrong: ['This painting is as colourful than that one.', 'This painting is colourful as that one.', 'This painting as colourful as that one.'] },
    { title: 'Future simple passive', meaning: 'Nhấn mạnh đối tượng nhận hành động trong tương lai.', structure: ['S + will be + past participle', 'S + will not be + past participle'], use: 'Dùng khi người thực hiện không quan trọng hoặc đã rõ.', examples: [{ english: 'Clean energy will be used more widely.', vietnamese: 'Năng lượng sạch sẽ được sử dụng rộng rãi hơn.' }], note: 'Cần đủ will be và quá khứ phân từ.', correct: 'Clean energy will be used more widely.', wrong: ['Clean energy will used more widely.', 'Clean energy will be use more widely.', 'Clean energy will use more widely.'] },
  ],
  11: [
    { title: 'Modal verbs: obligation and advice', meaning: 'Diễn tả nghĩa vụ, sự cần thiết hoặc lời khuyên.', structure: ['must/have to + V', 'should/ought to + V', 'must not + V'], use: 'Must not là cấm; do not have to là không cần thiết.', examples: [{ english: 'Teenagers should discuss problems calmly.', vietnamese: 'Thanh thiếu niên nên thảo luận vấn đề bình tĩnh.' }], note: 'Sau động từ khuyết thiếu dùng động từ nguyên mẫu.', correct: 'Teenagers should discuss problems calmly.', wrong: ['Teenagers should discussing problems calmly.', 'Teenagers should to discuss problems calmly.', 'Teenagers should discussed problems calmly.'] },
    { title: 'Perfect gerunds and participles', meaning: 'Nhấn mạnh hành động xảy ra trước một hành động khác.', structure: ['having + past participle', 'having been + past participle'], use: 'Dùng khi cần làm rõ thứ tự trước–sau giữa hai hành động.', examples: [{ english: 'Having finished the project, Minh took a break.', vietnamese: 'Sau khi hoàn thành dự án, Minh nghỉ giải lao.' }], note: 'Chủ ngữ ngầm của mệnh đề phân từ phải trùng với chủ ngữ chính.', correct: 'Having finished the project, Minh took a break.', wrong: ['Having finish the project, Minh took a break.', 'Finished having the project, Minh took a break.', 'Having finishing the project, Minh took a break.'] },
    { title: 'Cleft sentences', meaning: 'Nhấn mạnh người, vật, thời gian hoặc nơi chốn.', structure: ['It is/was + focus + that/who + clause'], use: 'Dùng who khi phần được nhấn mạnh là người; that dùng rộng hơn.', examples: [{ english: 'It was Lan who organised the campaign.', vietnamese: 'Chính Lan là người tổ chức chiến dịch.' }], note: 'Giữ nguyên thì của thông tin gốc trong phần mệnh đề.', correct: 'It was Lan who organised the campaign.', wrong: ['It Lan was who organised the campaign.', 'It was Lan organised the campaign.', 'Was Lan who it organised the campaign.'] },
    { title: 'Conditional sentences type 1', meaning: 'Nói về điều kiện có thể xảy ra trong hiện tại hoặc tương lai.', structure: ['If + present simple, S + will/can/may + V'], use: 'Không dùng will trong mệnh đề if thông thường.', examples: [{ english: 'If cities plant more trees, the air will improve.', vietnamese: 'Nếu thành phố trồng thêm cây, không khí sẽ tốt hơn.' }], note: 'Mệnh đề if dùng hiện tại đơn.', correct: 'If cities plant more trees, the air will improve.', wrong: ['If cities will plant more trees, the air improves.', 'If cities planted more trees, the air will improve.', 'If cities plant more trees, the air improving.'] },
  ],
  12: [
    { title: 'Past simple and past continuous', meaning: 'Kết hợp hành động đang diễn ra với sự việc xen vào trong quá khứ.', structure: ['S + was/were + V-ing when S + V2/ed', 'While S + was/were + V-ing, S + V2/ed'], use: 'Past continuous tạo bối cảnh; past simple nêu sự việc xen vào.', examples: [{ english: 'While the scientist was speaking, the lights went out.', vietnamese: 'Trong lúc nhà khoa học phát biểu, đèn tắt.' }], note: 'Không dùng V2 sau was/were trong thì tiếp diễn.', correct: 'While the scientist was speaking, the lights went out.', wrong: ['While the scientist spoke, the lights were go out.', 'While the scientist was speak, the lights went out.', 'While the scientist speaking, the lights went out.'] },
    { title: 'Articles: a, an and the', meaning: 'Xác định danh từ chung, lần đầu nhắc đến hoặc đối tượng cụ thể.', structure: ['a/an + singular countable noun', 'the + specific or unique noun', 'zero article + plural/general noun'], use: 'Chọn a/an theo âm đầu, không chỉ theo chữ cái.', examples: [{ english: 'She hopes to become an engineer in the future.', vietnamese: 'Cô ấy hy vọng trở thành kỹ sư.' }], note: 'Engineer bắt đầu bằng nguyên âm nên dùng an.', correct: 'She hopes to become an engineer in the future.', wrong: ['She hopes to become a engineer in the future.', 'She hopes to become the engineer in future generally.', 'She hopes to become engineer an in the future.'] },
    { title: 'Reported speech', meaning: 'Thuật lại lời nói mà không trích dẫn nguyên văn.', structure: ['S + said (that) + clause', 'S + told + object + (that) + clause', 'S + asked + if/wh-word + clause'], use: 'Thường lùi thì và đổi đại từ, trạng từ thời gian cho phù hợp.', examples: [{ english: 'Mai said that she was preparing for an interview.', vietnamese: 'Mai nói rằng cô ấy đang chuẩn bị phỏng vấn.' }], note: 'Tell cần tân ngữ; say không bắt buộc có tân ngữ.', correct: 'Mai said that she was preparing for an interview.', wrong: ['Mai said me that she was preparing for an interview.', 'Mai told that she preparing for an interview.', 'Mai said that I is preparing for an interview.'] },
    { title: 'Relative clauses', meaning: 'Bổ sung thông tin về người, vật, nơi chốn hoặc thời gian.', structure: ['person + who/that', 'thing + which/that', 'place + where', 'time + when'], use: 'Mệnh đề xác định không dùng dấu phẩy; mệnh đề không xác định có dấu phẩy.', examples: [{ english: 'The course that I chose develops practical skills.', vietnamese: 'Khóa học tôi chọn phát triển kỹ năng thực tế.' }], note: 'Không dùng what thay cho who/which sau danh từ có trước.', correct: 'The course that I chose develops practical skills.', wrong: ['The course what I chose develops practical skills.', 'The course who I chose develops practical skills.', 'The course that I chose it develops practical skills.'] },
  ],
};

const units: Record<ExtendedGrade, UnitSeed[]> = {
  6: [
    ['My New School', [['classmate','bạn cùng lớp','a student in the same class','My new classmate sits next to me.','noun'],['timetable','thời khóa biểu','a plan showing lesson times','Our timetable has English on Monday.','noun'],['laboratory','phòng thí nghiệm','a room for scientific work','We do experiments in the laboratory.','noun'],['creative','sáng tạo','able to produce new ideas','The creative students designed a poster.','adjective']]],
    ['My House', [['apartment','căn hộ','a set of rooms for living in','Their apartment has a bright balcony.','noun'],['furniture','đồ nội thất','movable objects used in a room','The wooden furniture looks simple.','noun'],['cupboard','tủ có ngăn','a cabinet used for storage','The cups are in the cupboard.','noun'],['comfortable','thoải mái','making someone feel relaxed','This chair is comfortable.','adjective']]],
    ['My Friends', [['generous','hào phóng','willing to give and share','Our generous friend shares her notes.','adjective'],['patient','kiên nhẫn','able to wait calmly','A patient partner listens carefully.','adjective'],['reliable','đáng tin cậy','able to be trusted','Nam is reliable and keeps his promises.','adjective'],['appearance','ngoại hình','the way someone looks','Clothes are only one part of appearance.','noun']]],
    ['My Neighbourhood', [['square','quảng trường','an open public space in a town','Families meet in the town square.','noun'],['convenient','thuận tiện','easy and useful for a purpose','The bus stop is convenient for students.','adjective'],['crowded','đông đúc','full of people','The market is crowded at weekends.','adjective'],['direction','phương hướng','the way that leads somewhere','A local resident gave us directions.','noun']]],
    ['Natural Wonders of Viet Nam', [['waterfall','thác nước','water falling over a high edge','The waterfall is powerful after rain.','noun'],['landscape','phong cảnh','the visible features of an area','The mountain landscape is spectacular.','noun'],['cave','hang động','a natural underground chamber','The guide led us into the cave.','noun'],['protect','bảo vệ','to keep someone or something safe','Visitors must protect the natural site.','verb']]],
    ['Our Tet Holiday', [['celebrate','ăn mừng','to mark a special event','Families celebrate Tet together.','verb'],['decoration','đồ trang trí','an object that makes a place attractive','Red decorations brighten the room.','noun'],['lucky money','tiền lì xì','money given in a red envelope','Children receive lucky money at Tet.','noun phrase'],['tradition','truyền thống','a custom passed between generations','Making special food is a family tradition.','noun']]],
    ['Television', [['programme','chương trình','a show broadcast on television','This science programme is informative.','noun'],['documentary','phim tài liệu','a factual film or programme','We watched a wildlife documentary.','noun'],['viewer','người xem','a person who watches television','Young viewers enjoy the quiz.','noun'],['educational','mang tính giáo dục','helping people learn','The channel offers educational videos.','adjective']]],
    ['Sports and Games', [['tournament','giải đấu','a series of sports contests','Our team entered a football tournament.','noun'],['equipment','dụng cụ','items needed for an activity','Check the sports equipment before class.','noun'],['competition','cuộc thi đấu','an event in which people try to win','The swimming competition starts at nine.','noun'],['active','năng động','physically busy and energetic','An active lifestyle supports good health.','adjective']]],
    ['Cities of the World', [['capital','thủ đô','the main city of a country','Canberra is the capital of Australia.','noun'],['landmark','địa danh nổi tiếng','an important recognisable place','The bridge is a famous landmark.','noun'],['culture','văn hóa','the ideas and customs of a society','Food is an important part of culture.','noun'],['explore','khám phá','to travel around and learn about a place','We explored the old town on foot.','verb']]],
    ['Our Houses in the Future', [['solar panel','tấm pin mặt trời','a device that changes sunlight into energy','Solar panels power the future house.','noun phrase'],['automatic','tự động','working without direct human control','The automatic door opens quietly.','adjective'],['smart appliance','thiết bị thông minh','a connected household machine','A smart appliance can save electricity.','noun phrase'],['prediction','dự đoán','a statement about the future','Her prediction about homes was interesting.','noun']]],
    ['Our Greener World', [['recycle','tái chế','to process waste for reuse','We recycle paper and metal at school.','verb'],['reusable','có thể tái sử dụng','able to be used many times','Bring a reusable bottle to class.','adjective'],['pollution','ô nhiễm','harmful substances in the environment','Cycling helps reduce air pollution.','noun'],['reduce','giảm','to make something smaller in amount','We should reduce plastic waste.','verb']]],
    ['Robots', [['robotic','thuộc rô-bốt','connected with robots','The robotic arm lifts small boxes.','adjective'],['perform','thực hiện','to carry out a task','This robot can perform simple tasks.','verb'],['sensor','cảm biến','a device that detects changes','A sensor helps the robot avoid walls.','noun'],['assist','hỗ trợ','to help someone','Robots may assist doctors in hospitals.','verb']]],
  ],
  7: [
    ['Hobbies', [['collect','sưu tầm','to gather items as an interest','I collect postcards from different cities.','verb'],['model making','làm mô hình','the activity of building small copies','Model making requires patience.','noun phrase'],['creative','sáng tạo','using imagination to make something','Painting is a creative hobby.','adjective'],['benefit','lợi ích','a helpful result','Reading has many benefits.','noun']]],
    ['Healthy Living', [['balanced diet','chế độ ăn cân bằng','food containing suitable nutrients','A balanced diet includes vegetables.','noun phrase'],['sunburn','cháy nắng','red painful skin caused by sunlight','Wear a hat to avoid sunburn.','noun'],['allergy','dị ứng','a harmful reaction to a substance','This food may cause an allergy.','noun'],['maintain','duy trì','to keep at the same level','Exercise helps maintain good health.','verb']]],
    ['Community Service', [['volunteer','tình nguyện viên','a person who works without payment','Each volunteer packed food boxes.','noun'],['donate','quyên góp','to give something to help others','Students donate books to the library.','verb'],['homeless','vô gia cư','without a permanent home','The project supports homeless people.','adjective'],['community','cộng đồng','people living in one area','Our community planted a public garden.','noun']]],
    ['Music and Arts', [['performance','màn biểu diễn','an act presented to an audience','The performance began with a song.','noun'],['portrait','tranh chân dung','a picture of a person','The artist painted a family portrait.','noun'],['composer','nhà soạn nhạc','a person who writes music','The composer created a gentle melody.','noun'],['exhibition','triển lãm','a public display of art','We visited a student art exhibition.','noun']]],
    ['Food and Drink', [['ingredient','nguyên liệu','one item used to make food','Fresh herbs are an important ingredient.','noun'],['recipe','công thức nấu ăn','instructions for preparing food','Follow the recipe carefully.','noun'],['delicious','ngon','having a very pleasant taste','The noodle soup smells delicious.','adjective'],['portion','khẩu phần','an amount of food for one person','This portion is enough for me.','noun']]],
    ['A Visit to a School', [['facility','cơ sở vật chất','a place or equipment for an activity','The school has modern sports facilities.','noun'],['exchange student','học sinh trao đổi','a learner studying temporarily abroad','An exchange student joined our class.','noun phrase'],['uniform','đồng phục','special clothes worn by a group','Students wear a blue uniform.','noun'],['experience','trải nghiệm','knowledge gained by doing something','The visit was a valuable experience.','noun']]],
    ['Traffic', [['pedestrian','người đi bộ','a person travelling on foot','Pedestrians should use the crossing.','noun'],['helmet','mũ bảo hiểm','protective head covering','Always wear a helmet on a bicycle.','noun'],['congestion','ùn tắc','a state of being too crowded','Traffic congestion is worse at rush hour.','noun'],['obey','tuân thủ','to follow a rule or command','Drivers must obey traffic signs.','verb']]],
    ['Films', [['director','đạo diễn','the person controlling a film','The director discussed the final scene.','noun'],['plot','cốt truyện','the main events of a story','The film has an exciting plot.','noun'],['character','nhân vật','a person in a story','My favourite character is the young pilot.','noun'],['entertaining','mang tính giải trí','enjoyable and amusing','The comedy was entertaining.','adjective']]],
    ['Festivals Around the World', [['parade','diễu hành','a public procession for celebration','A colourful parade crossed the town.','noun'],['costume','trang phục','special clothes for an event','The dancers wore traditional costumes.','noun'],['celebration','lễ kỷ niệm','an enjoyable event marking an occasion','The celebration lasted two days.','noun'],['take place','diễn ra','to happen','The festival takes place in spring.','verb phrase']]],
    ['Energy Sources', [['renewable','tái tạo được','naturally replaced and sustainable','Wind is a renewable energy source.','adjective'],['fossil fuel','nhiên liệu hóa thạch','coal oil or gas formed underground','Burning fossil fuels releases carbon.','noun phrase'],['efficient','hiệu quả','working well without waste','LED lights are energy-efficient.','adjective'],['generate','tạo ra','to produce energy or power','The panels generate electricity.','verb']]],
    ['Travelling in the Future', [['driverless','không người lái','operating without a human driver','A driverless bus follows a planned route.','adjective'],['vehicle','phương tiện','a machine used for transport','The electric vehicle is nearly silent.','noun'],['hyperloop','hệ thống vận chuyển siêu tốc','a proposed high-speed transport system','A hyperloop may connect distant cities.','noun'],['convenient','thuận tiện','easy and suitable to use','Public transport should be convenient.','adjective']]],
    ['English-speaking Countries', [['native speaker','người bản ngữ','a person who learned a language from birth','A native speaker recorded the guide.','noun phrase'],['official language','ngôn ngữ chính thức','a language recognised by a government','English is an official language there.','noun phrase'],['multicultural','đa văn hóa','including several cultures','The city has a multicultural population.','adjective'],['symbol','biểu tượng','an object representing an idea or place','The leaf is a national symbol.','noun']]],
  ],
  11: [
    ['The Generation Gap', [['generation gap','khoảng cách thế hệ','differences between age groups','Open conversations can narrow the generation gap.','noun phrase'],['conflict','xung đột','a serious disagreement','They resolved the conflict calmly.','noun'],['value','giá trị','a principle considered important','Respect is an important family value.','noun'],['compromise','thỏa hiệp','an agreement in which each side gives something up','Both sides reached a compromise.','noun']]],
    ['Relationships', [['sympathetic','cảm thông','showing understanding of another person','A sympathetic friend listened carefully.','adjective'],['trust','sự tin tưởng','belief in someone’s honesty','Trust grows through honest communication.','noun'],['argument','cuộc tranh luận','an angry disagreement','They settled the argument before class.','noun'],['reconcile','làm hòa','to restore a friendly relationship','The cousins reconciled after talking.','verb']]],
    ['Becoming Independent', [['self-reliant','tự lập','able to depend on oneself','A self-reliant student plans ahead.','adjective'],['budget','ngân sách','a plan for spending money','She made a monthly budget.','noun'],['prioritise','ưu tiên','to decide what is most important','Learn to prioritise urgent tasks.','verb'],['responsibility','trách nhiệm','a duty that someone must handle','Cooking dinner is his responsibility today.','noun']]],
    ['Caring for Those in Need', [['accessible','dễ tiếp cận','easy to enter use or understand','The ramp makes the building accessible.','adjective'],['donation','khoản quyên góp','something given to help','The charity received a generous donation.','noun'],['disability','khuyết tật','a condition limiting some activities','Technology can support people with a disability.','noun'],['inclusive','hòa nhập','welcoming people with different needs','The club organises inclusive activities.','adjective']]],
    ['Being Part of ASEAN', [['member state','quốc gia thành viên','a country belonging to an organisation','Each member state sends a representative.','noun phrase'],['cooperation','sự hợp tác','working together for a shared purpose','Regional cooperation supports development.','noun'],['diversity','sự đa dạng','the presence of many different forms','ASEAN celebrates cultural diversity.','noun'],['initiative','sáng kiến','a new plan intended to solve a problem','Students proposed a green initiative.','noun']]],
    ['Global Warming', [['carbon footprint','dấu chân carbon','the emissions caused by a person or activity','Cycling reduces your carbon footprint.','noun phrase'],['emission','khí thải','gas released into the air','The policy limits harmful emissions.','noun'],['deforestation','nạn phá rừng','large-scale removal of forests','Deforestation destroys animal habitats.','noun'],['mitigate','giảm nhẹ','to make something less harmful','Trees help mitigate climate change.','verb']]],
    ['Further Education', [['qualification','bằng cấp','an official record of achievement','The course leads to a useful qualification.','noun'],['scholarship','học bổng','money supporting a student’s education','She applied for a university scholarship.','noun'],['vocational','thuộc nghề nghiệp','providing practical job skills','He chose a vocational training programme.','adjective'],['enrol','ghi danh','to officially join a course','Students can enrol online.','verb']]],
    ['Our World Heritage Sites', [['heritage','di sản','valuable traditions or places from the past','The temple is part of our cultural heritage.','noun'],['preserve','bảo tồn','to keep something safe from damage','The project helps preserve the old walls.','verb'],['archaeological','thuộc khảo cổ','connected with studying ancient remains','The team examined an archaeological site.','adjective'],['authentic','nguyên bản','real and not copied','The museum protects authentic objects.','adjective']]],
    ['Cities of the Future', [['infrastructure','cơ sở hạ tầng','basic systems serving a city','Modern infrastructure improves public transport.','noun'],['sustainable','bền vững','able to continue without harming resources','The plan supports sustainable development.','adjective'],['urban planner','nhà quy hoạch đô thị','a person who designs city development','An urban planner presented the proposal.','noun phrase'],['pedestrian zone','khu đi bộ','an area where cars are restricted','The pedestrian zone is safe and lively.','noun phrase']]],
    ['Healthy Lifestyle and Longevity', [['longevity','tuổi thọ','a long duration of life','Regular activity may support longevity.','noun'],['nutritious','bổ dưỡng','containing useful nutrients','Choose nutritious meals at school.','adjective'],['sedentary','ít vận động','involving too much sitting','A sedentary lifestyle can harm health.','adjective'],['well-being','sức khỏe và hạnh phúc','a state of being healthy and comfortable','Sleep is important for well-being.','noun']]],
  ],
  12: [
    ['Life Stories We Admire', [['influential','có ảnh hưởng','having a strong effect on others','She became an influential scientist.','adjective'],['dedication','sự cống hiến','continued effort toward a purpose','His dedication inspired younger athletes.','noun'],['achievement','thành tựu','something successfully completed','The discovery was a major achievement.','noun'],['overcome','vượt qua','to succeed in dealing with difficulty','She overcame many early challenges.','verb']]],
    ['A Multicultural World', [['identity','bản sắc','the qualities defining a person or group','Language is part of cultural identity.','noun'],['diversity','sự đa dạng','a range of different people or ideas','The festival celebrates cultural diversity.','noun'],['integrate','hòa nhập','to become part of a group','New residents integrate through local activities.','verb'],['stereotype','định kiến khuôn mẫu','a fixed oversimplified belief','Travel can challenge a stereotype.','noun']]],
    ['Green Living', [['biodegradable','có thể phân hủy sinh học','able to decay naturally','The café uses biodegradable packaging.','adjective'],['conserve','bảo tồn, tiết kiệm','to protect or avoid wasting a resource','Short showers conserve water.','verb'],['consumption','sự tiêu thụ','the use of energy or goods','The building reduced energy consumption.','noun'],['eco-friendly','thân thiện môi trường','causing little environmental harm','We chose eco-friendly cleaning products.','adjective']]],
    ['Urbanisation', [['urbanisation','đô thị hóa','the growth of towns and cities','Urbanisation creates new opportunities and pressures.','noun'],['migrate','di cư','to move to another place to live or work','Many workers migrate to growing cities.','verb'],['housing shortage','thiếu nhà ở','a lack of available homes','The city is addressing a housing shortage.','noun phrase'],['megacity','siêu đô thị','a city with a very large population','Public transport is essential in a megacity.','noun']]],
    ['The World of Work', [['internship','kỳ thực tập','temporary work for learning a profession','The internship provided practical experience.','noun'],['recruiter','nhà tuyển dụng','a person who finds employees','The recruiter asked about teamwork.','noun'],['qualification','bằng cấp','an official skill or achievement','The position requires a technical qualification.','noun'],['workplace','nơi làm việc','a place where people work','Respect improves the workplace.','noun']]],
    ['Artificial Intelligence', [['algorithm','thuật toán','a set of steps used by a computer','The algorithm sorts the results quickly.','noun'],['automation','tự động hóa','using technology to perform tasks','Automation changed the production line.','noun'],['ethical','thuộc đạo đức','morally right and responsible','Designers discussed the ethical use of data.','adjective'],['innovation','sự đổi mới','a useful new idea or method','The device is an impressive innovation.','noun']]],
    ['The World of Mass Media', [['broadcast','phát sóng','to send programmes by television or radio','The station will broadcast the debate.','verb'],['headline','tiêu đề tin','the title of a news report','The headline summarised the main event.','noun'],['credible','đáng tin','able to be believed','Check whether the source is credible.','adjective'],['misinformation','thông tin sai lệch','false information spread as fact','Media literacy helps identify misinformation.','noun']]],
    ['Wildlife Conservation', [['biodiversity','đa dạng sinh học','the variety of living things','The forest supports rich biodiversity.','noun'],['poaching','săn trộm','illegal hunting of wild animals','Rangers work to prevent poaching.','noun'],['endangered','có nguy cơ tuyệt chủng','at serious risk of disappearing','The programme protects endangered turtles.','adjective'],['restore','khôi phục','to return something to a healthy condition','Volunteers restore damaged wetlands.','verb']]],
    ['Career Paths', [['aptitude','năng khiếu','a natural ability to learn a skill','She has an aptitude for design.','noun'],['career path','lộ trình nghề nghiệp','a sequence of jobs and development','Mentors can clarify a career path.','noun phrase'],['apprenticeship','chương trình học nghề','paid practical training with study','He began an apprenticeship in engineering.','noun'],['transferable skill','kỹ năng chuyển đổi','an ability useful in many jobs','Communication is a transferable skill.','noun phrase']]],
    ['Lifelong Learning', [['lifelong','suốt đời','continuing through a person’s life','Curiosity supports lifelong learning.','adjective'],['upskill','nâng cao kỹ năng','to learn additional work skills','Employees upskill through short courses.','verb'],['self-directed','tự định hướng','planned and managed by the learner','The platform supports self-directed study.','adjective'],['adaptable','có khả năng thích nghi','able to change for new conditions','Adaptable workers learn new tools quickly.','adjective']]],
  ],
};

const pronunciations: { title: string; guidance: string; examples: string; options: [string, string, string, string]; underlines?: [string, string, string, string]; answer: number }[] = [
  { title: '/s/ and /ʃ/', guidance: 'Keep /s/ narrow and forward; round the lips slightly for /ʃ/.', examples: 'see /siː/ · city /ˈsɪti/ · she /ʃiː/', options: ['see','city','science','she'], underlines: ['s','c','s','sh'], answer: 3 },
  { title: 'final -s', guidance: 'Final -s may sound /s/, /z/ or /ɪz/ depending on the final sound.', examples: 'books /s/ · pens /z/ · watches /ɪz/', options: ['books','maps','cups','pens'], underlines: ['s','s','s','s'], answer: 3 },
  { title: 'final -ed', guidance: 'Final -ed is /t/, /d/ or /ɪd/.', examples: 'washed /t/ · played /d/ · wanted /ɪd/', options: ['washed','looked','helped','wanted'], underlines: ['ed','ed','ed','ed'], answer: 3 },
  { title: 'word stress', guidance: 'Listen for the strongest syllable and avoid stressing every syllable equally.', examples: 'TAble · reLAX · eduCAtion', options: ['teacher','student','table','today'], answer: 3 },
];

function question(id: number, skillArea: NonNullable<Question['skillArea']>, prompt: string, options: string[], answer: number | string | string[], explanation: string, extra: Partial<Question> = {}): Question {
  return { id, section: skillArea === 'Reading' ? 'Reading' : skillArea === 'Writing' ? 'Writing' : 'Language Focus', skillArea, prompt, options, answer, explanation, ...extra };
}

function buildUnit(grade: ExtendedGrade, unit: number, seed: UnitSeed): { exam: Exam; lesson: GrammarLesson; enrichment: UnitEnrichment } {
  const [title, vocabulary] = seed;
  const grammar = grammarByGrade[grade][(unit - 1) % grammarByGrade[grade].length];
  const pronunciation = pronunciations[(unit - 1) % pronunciations.length];
  const allDefinitions = vocabulary.map((item) => item[2]);
  const questions: Question[] = [
    question(1, 'Pronunciation', 'Choose the word whose underlined part is pronounced differently.', pronunciation.options, pronunciation.answer, `The target sound is different in “${pronunciation.options[pronunciation.answer]}”.`, { underlines: pronunciation.underlines }),
  ];
  vocabulary.forEach((item, index) => {
    const distractors = allDefinitions.filter((_, candidate) => candidate !== index);
    questions.push(question(questions.length + 1, 'Vocabulary', `Which definition best matches “${item[0]}”?`, [item[2], ...distractors], 0, `“${item[0]}” means ${item[2]}.`));
    questions.push(question(questions.length + 1, 'Vocabulary', item[3].replace(new RegExp(item[0], 'i'), '___'), [item[0], ...vocabulary.filter((_, candidate) => candidate !== index).map((entry) => entry[0])], 0, `The context requires “${item[0]}”. ${item[3]}`));
  });
  questions.push(
    question(questions.length + 1, 'Grammar', `Which sentence correctly uses ${grammar.title}?`, [grammar.correct, ...grammar.wrong], 0, grammar.note),
    question(questions.length + 1, 'Grammar', `Choose the correctly formed sentence for the focus “${grammar.title}”.`, [grammar.correct, grammar.wrong[1], grammar.wrong[2], grammar.wrong[0]], 0, `${grammar.correct} ${grammar.use}`),
    question(questions.length + 1, 'Grammar', `Which sentence has no grammar error?`, [grammar.wrong[0], grammar.correct, grammar.wrong[1], grammar.wrong[2]], 1, `${grammar.correct} ${grammar.note}`),
    question(questions.length + 1, 'Grammar', `Select the best model sentence for this unit's grammar.`, [grammar.wrong[2], grammar.wrong[0], grammar.correct, grammar.wrong[1]], 2, `${grammar.correct} ${grammar.use}`),
    question(questions.length + 1, 'Grammar', `A learner wants to use “${grammar.title}”. Which version is accurate?`, [grammar.wrong[1], grammar.wrong[2], grammar.wrong[0], grammar.correct], 3, `${grammar.correct} ${grammar.note}`),
    question(questions.length + 1, 'Grammar', 'Choose the sentence a careful editor would keep.', [grammar.correct, grammar.wrong[2], grammar.wrong[0], grammar.wrong[1]], 0, `${grammar.correct} ${grammar.note}`),
    question(questions.length + 1, 'Grammar', 'Which option follows the target structure and word order?', [grammar.wrong[0], grammar.correct, grammar.wrong[2], grammar.wrong[1]], 1, `${grammar.correct} ${grammar.use}`),
    question(questions.length + 1, 'Grammar', 'Choose the grammatically complete option.', [grammar.wrong[1], grammar.wrong[0], grammar.correct, grammar.wrong[2]], 2, `${grammar.correct} ${grammar.note}`),
    question(questions.length + 1, 'Grammar', 'Which option would be suitable in a formal English assignment?', [grammar.wrong[2], grammar.wrong[1], grammar.wrong[0], grammar.correct], 3, `${grammar.correct} ${grammar.use}`),
    question(questions.length + 1, 'Grammar', `Review “${grammar.title}”. Which sentence is accurate?`, [grammar.correct, grammar.wrong[0], grammar.wrong[2], grammar.wrong[1]], 0, `${grammar.correct} ${grammar.note}`),
  );
  const names = vocabulary.map((item) => item[0]);
  const passage = `Students in Class ${grade}A planned a small project called “${title} in Action”. First, they discussed why ${names[0]} and ${names[1]} mattered in everyday life. Teams then created an information corner and used ${names[2]} in a practical demonstration. Instead of copying material, they interviewed people, checked facts and wrote their own short explanations. Their teacher asked every group to improve one detail after receiving feedback. At the final sharing session, visitors said the project was clear, useful and memorable. The students concluded that careful teamwork can turn classroom language into real communication.`;
  questions.push(
    question(questions.length + 1, 'Reading', 'What is the main purpose of the class project?', ['To use unit language in a practical project','To copy an article without changes','To cancel the final sharing session','To compete for individual prizes'], 0, 'The project connects classroom language with practical communication.'),
    question(questions.length + 1, 'Reading', 'How did students collect information?', ['They guessed every fact','They interviewed people and checked facts','They copied one source','They avoided asking questions'], 1, 'The passage explicitly says they interviewed people and checked facts.'),
    question(questions.length + 1, 'Reading', 'What did the teacher ask each group to do?', ['Add ten pages','Change the project title','Improve one detail after feedback','Work without a team'], 2, 'Each group improved one detail after feedback.'),
    question(questions.length + 1, 'Reading', 'How did visitors describe the project?', ['Confusing and incomplete','Too long to understand','Unrelated to the unit','Clear, useful and memorable'], 3, 'These three adjectives appear in the passage.'),
    question(questions.length + 1, 'Reading', 'Which statement is true?', ['Students wrote their own explanations','Students did not share their work','Only the teacher used the vocabulary','The teams ignored feedback'], 0, 'Students checked facts and wrote original explanations.'),
    question(questions.length + 1, 'Writing', 'Rewrite the model sentence exactly with correct grammar.', [], grammar.correct, grammar.note, { kind: 'typed', template: 'Model: [[0]]', acceptedAnswers: [[grammar.correct]], hint: grammar.structure.join(' · ') }),
    question(questions.length + 1, 'Writing', `Write the unit title in English.`, [], title, `The unit title is “${title}”.`, { kind: 'typed', template: 'Unit ${unit}: [[0]]', acceptedAnswers: [[title]], hint: `It begins with “${title.split(' ')[0]}”.` }),
    question(questions.length + 1, 'Looking Back', `Choose the word that best completes: “The project helped us understand ___.”`, [vocabulary[0][0], vocabulary[1][0], vocabulary[2][0], vocabulary[3][0]], 0, `“${vocabulary[0][0]}” is a key word in this unit.`),
  );
  const distributed = distributeAnswers(questions, `extended-${grade}-${unit}`);
  const lesson: GrammarLesson = { unit, topics: [grammar], exercises: distributed.filter((item) => item.skillArea === 'Grammar').slice(0, 10) };
  const enrichment: UnitEnrichment = {
    vocabulary: vocabulary.map(([word, vietnamese, , example, partOfSpeech]) => ({ word, ipa: '—', partOfSpeech: partOfSpeech ?? 'word', meaning: vietnamese, example })),
    pronunciation: { ...pronunciation, explanation: `“${pronunciation.options[pronunciation.answer]}” contains the different target sound.`, prompt: 'Choose the word whose underlined part is pronounced differently.' },
  };
  return {
    exam: { id: grade * 1000 + unit, unit, menuLabel: `Unit ${unit} · ${title}`, menuGroup: 'unit', title: `English ${grade} · Unit ${unit}: ${title}`, theme: `${grammar.title} · ${distributed.length} câu`, sourceNote: 'Nội dung và câu hỏi được biên soạn mới theo định hướng chương trình phổ thông; không sao chép nguyên văn từ sách hoặc đề thương mại.', passageTitle: `${title} in Action`, passage, questions: distributed, reviewNotes: [{ title: grammar.title, rule: grammar.structure.join(' · '), example: grammar.correct }] },
    lesson,
    enrichment,
  };
}

function sampleQuestions(exams: Exam[], predicate: (exam: Exam) => boolean, count: number, seed: string) {
  const source = exams.filter(predicate).flatMap((exam) => exam.questions);
  const picked: Question[] = [];
  for (let offset = 0; picked.length < count && offset < source.length * 2; offset += 1) {
    const candidate = source[(offset * 7 + seed.length * 3) % source.length];
    if (!picked.some((item) => item.prompt === candidate.prompt && item.answer === candidate.answer)) picked.push({ ...candidate, id: picked.length + 1 });
  }
  return distributeAnswers(picked, seed);
}

function assessment(grade: ExtendedGrade, id: number, menuGroup: NonNullable<Exam['menuGroup']>, label: string, exams: Exam[], predicate: (exam: Exam) => boolean, count = 40): Exam {
  const questions = sampleQuestions(exams, predicate, count, `${grade}-${menuGroup}-${id}`);
  return { id, menuGroup, menuLabel: label, title: `English ${grade} · ${label}`, theme: 'Bài tổng hợp · Không gồm phần nghe', sourceNote: 'Bộ đề tổng hợp được tạo từ ngân hàng câu hỏi nguyên bản của website và tự động tránh câu trùng trong cùng một bài.', passageTitle: 'Integrated review', passage: 'Read each question carefully and use the vocabulary, grammar and reading strategies practised in the units.', questions };
}

const generated = Object.fromEntries((Object.keys(units) as unknown as ExtendedGrade[]).map((grade) => {
  const built = units[grade].map((seed, index) => buildUnit(grade, index + 1, seed));
  return [grade, built];
})) as Record<ExtendedGrade, ReturnType<typeof buildUnit>[]>;

export const extendedGrammarLessons = Object.fromEntries((Object.keys(generated) as unknown as ExtendedGrade[]).map((grade) => [grade, Object.fromEntries(generated[grade].map((item) => [item.lesson.unit, item.lesson]))])) as Record<ExtendedGrade, Record<number, GrammarLesson>>;
export const extendedEnrichment = Object.fromEntries((Object.keys(generated) as unknown as ExtendedGrade[]).map((grade) => [grade, Object.fromEntries(generated[grade].map((item) => [item.lesson.unit, item.enrichment]))])) as Record<ExtendedGrade, Record<number, UnitEnrichment>>;
export const extendedVocabulary = Object.fromEntries((Object.keys(units) as unknown as ExtendedGrade[]).map((grade) => [grade, units[grade].flatMap(([, words]) => words.map(([word, meaning, , example]) => ({ word, meaning, example })))])) as Record<ExtendedGrade, VocabularyItem[]>;

export const extendedExams = Object.fromEntries((Object.keys(generated) as unknown as ExtendedGrade[]).map((grade) => {
  const unitExams = generated[grade].map((item) => item.exam);
  const split = Math.ceil(unitExams.length / 2);
  const extras = [
    assessment(grade, grade * 1000 + 90, 'review', 'Ôn tập tổng hợp', unitExams, () => true, 25),
    assessment(grade, grade * 1000 + 91, 'midterm', 'Giữa kỳ I · Đề tổng hợp', unitExams, (exam) => (exam.unit ?? 0) <= Math.ceil(split / 2)),
    assessment(grade, grade * 1000 + 92, 'final', 'Cuối kỳ I · Đề tổng hợp', unitExams, (exam) => (exam.unit ?? 0) <= split),
    assessment(grade, grade * 1000 + 93, 'midterm2', 'Giữa kỳ II · Đề tổng hợp', unitExams, (exam) => (exam.unit ?? 0) > split && (exam.unit ?? 0) <= split + Math.ceil((unitExams.length - split) / 2)),
    assessment(grade, grade * 1000 + 94, 'final2', 'Cuối kỳ II · Đề tổng hợp', unitExams, () => true),
  ];
  return [grade, distributeExams([...unitExams, ...extras])];
})) as Record<ExtendedGrade, Exam[]>;
