import type { Question } from './exams';
import { distributeAnswers } from './answer-distribution';
import type { GrammarLesson, GrammarTopic } from './grammar-lessons9';

type Row = [prompt: string, correct: string, wrong1: string, wrong2: string, wrong3: string, explanation: string];

const topic = (
  title: string,
  meaning: string,
  structure: string[],
  use: string,
  examples: [english: string, vietnamese: string][],
  note: string,
): GrammarTopic => ({ title, meaning, structure, use, examples: examples.map(([english, vietnamese]) => ({ english, vietnamese })), note });

const exercise = (rows: Row[], unit: number): Question[] => distributeAnswers(rows.map(([prompt, correct, wrong1, wrong2, wrong3, explanation], index) => ({
  id: index + 1,
  section: 'Language Focus' as const,
  prompt,
  options: [correct, wrong1, wrong2, wrong3],
  answer: 0,
  explanation,
})), `grammar-8-unit-${unit}`);

export const grammarLessons8: Record<number, GrammarLesson> = {
  1: {
    unit: 1,
    topics: [topic('Động từ chỉ sở thích + V-ing/to V', 'Nói về hoạt động mình thích, yêu thích hoặc không thích trong thời gian rảnh.', ['S + like/love/prefer/hate + V-ing hoặc to V', 'S + enjoy/detest/avoid + V-ing', 'Do/Does + S + like + V-ing/to V?'], 'Sau enjoy, detest và avoid phải dùng V-ing. Sau like, love, prefer và hate có thể dùng V-ing hoặc to V trong nhiều ngữ cảnh; khi nói sở thích chung, V-ing rất tự nhiên.', [['I enjoy making paper flowers.', 'Tôi thích làm hoa giấy.'], ['My brother likes to play chess after school.', 'Anh trai tôi thích chơi cờ sau giờ học.']], 'Sai: She enjoys to knit. Đúng: She enjoys knitting.')],
    exercises: exercise([
      ['Lan enjoys ___ origami.', 'doing', 'to do', 'do', 'did', 'Enjoy đi với V-ing: enjoys doing.'],
      ['My friends detest ___ in long queues.', 'waiting', 'to wait', 'wait', 'waited', 'Detest đi với V-ing: detest waiting.'],
      ['I like ___ the guitar at weekends.', 'playing', 'play', 'played', 'plays', 'Like có thể đi với V-ing khi nói sở thích: like playing.'],
      ['We avoid ___ too much time online.', 'spending', 'to spend', 'spend', 'spent', 'Avoid đi với V-ing: avoid spending.'],
      ['Does Mai love ___ comics?', 'reading', 'read', 'reads', 'to reading', 'Sau love có thể dùng V-ing: love reading.'],
      ['He hates ___ up early on Sundays.', 'getting', 'get', 'gets', 'to getting', 'Hate + V-ing diễn tả điều không thích nói chung.'],
      ['They prefer ___ outdoors.', 'playing', 'play', 'played', 'plays', 'Prefer có thể đi với V-ing khi nói sở thích chung.'],
      ['Choose the correct sentence.', 'She enjoys making models.', 'She enjoys make models.', 'She enjoys to making models.', 'She enjoy making models.', 'Enjoy + V-ing; chủ ngữ she cần enjoys.'],
      ['My father likes ___ photographs of birds.', 'taking', 'take', 'took', 'takes', 'Like + V-ing phù hợp khi nói về sở thích.'],
      ['The children enjoy ___ kites.', 'flying', 'fly', 'to fly', 'flew', 'Enjoy bắt buộc theo sau bởi V-ing: flying.'],
    ], 1),
  },
  2: {
    unit: 2,
    topics: [topic('So sánh hơn của trạng từ', 'So sánh cách hoặc mức độ hai hành động được thực hiện.', ['S + V + comparative adverb + than + người/vật so sánh', 'Trạng từ ngắn: hard → harder, fast → faster', 'Trạng từ dài: carefully → more carefully', 'Bất quy tắc: well → better, badly → worse'], 'Trạng từ bổ nghĩa cho động từ. Với trạng từ dài, dùng more/less; không tự thêm -er vào carefully hay slowly.', [['A horse runs faster than a buffalo.', 'Ngựa chạy nhanh hơn trâu.'], ['Mai works more carefully than her brother.', 'Mai làm việc cẩn thận hơn anh trai.']], 'Sai: more faster, carefulier. Đúng: faster, more carefully.')],
    exercises: exercise([
      ['A horse runs ___ than a buffalo.', 'faster', 'more fast', 'fastest', 'fastly', 'Fast là trạng từ ngắn; dạng so sánh hơn là faster.'],
      ['Lan works ___ than before.', 'more carefully', 'carefullier', 'most carefully', 'more careful', 'Carefully là trạng từ dài nên dùng more carefully.'],
      ['My brother speaks English ___ than I do.', 'better', 'gooder', 'more good', 'best', 'Well có dạng so sánh hơn bất quy tắc là better.'],
      ['The tractor moves ___ than the bicycle.', 'more slowly', 'slowlier', 'most slowly', 'more slow', 'Slowly là trạng từ dài nên dùng more slowly.'],
      ['We arrived ___ than our neighbours.', 'earlier', 'more early', 'earliest', 'earlyer', 'Early đổi y thành i rồi thêm -er: earlier.'],
      ['The team worked ___ this year than last year.', 'harder', 'hardly', 'more hard', 'hardest', 'Hard là trạng từ ngắn; harder là dạng so sánh hơn.'],
      ['Nam sings ___ than he did last year.', 'worse', 'badlier', 'more badly', 'worst', 'Badly có dạng so sánh hơn bất quy tắc là worse.'],
      ['Farmers now harvest rice ___ than in the past.', 'more efficiently', 'efficientlier', 'most efficiently', 'more efficient', 'Efficiently là trạng từ dài nên dùng more efficiently.'],
      ['Choose the correct sentence.', 'She drives more slowly than her dad.', 'She drives slowlier than her dad.', 'She drives more slow than her dad.', 'She drives most slowly than her dad.', 'Trong so sánh hơn với than, trạng từ dài dùng more + trạng từ.'],
      ['The children walked ___ than the adults.', 'more quickly', 'quicklier', 'most quickly', 'more quick', 'Quickly là trạng từ dài; dạng so sánh hơn là more quickly.'],
    ], 2),
  },
  3: {
    unit: 3,
    topics: [topic('Câu đơn và câu ghép', 'Câu đơn có một mệnh đề độc lập; câu ghép nối hai mệnh đề độc lập có quan hệ ý nghĩa.', ['Mệnh đề 1, + and/but/or/so + mệnh đề 2', 'And: bổ sung; but: tương phản; or: lựa chọn; so: kết quả', 'Mệnh đề 1; however, mệnh đề 2 (tương phản)'], 'Mỗi mệnh đề độc lập thường có chủ ngữ và động từ riêng. Dùng dấu phẩy trước liên từ khi nối hai mệnh đề đầy đủ; với however, cần dấu câu phù hợp.', [['I felt nervous, but my friends helped me.', 'Tôi thấy lo, nhưng bạn bè đã giúp tôi.'], ['The deadline is close, so we must plan carefully.', 'Hạn nộp đã gần, vì vậy chúng tôi phải lên kế hoạch cẩn thận.']], 'Sai: I was tired, however I continued. Đúng: I was tired; however, I continued.')],
    exercises: exercise([
      ['I was tired, ___ I finished the project.', 'but', 'so', 'or', 'and', 'Hai ý tương phản nên dùng but.'],
      ['The deadline is tomorrow, ___ we need to work now.', 'so', 'but', 'or', 'yet', 'Vế sau là kết quả nên dùng so.'],
      ['Would you like to call a friend, ___ would you prefer to rest?', 'or', 'and', 'so', 'but', 'Hai khả năng lựa chọn nối bằng or.'],
      ['Minh was worried, ___ his teacher gave him advice.', 'and', 'or', 'so', 'yet', 'Hai sự việc được bổ sung; and phù hợp.'],
      ['She practised hard, ___ she felt more confident.', 'so', 'but', 'or', 'yet', 'Tự tin hơn là kết quả của việc luyện tập.'],
      ['The forum is useful, ___ students must post politely.', 'but', 'so', 'or', 'and not', 'But diễn tả sự đối lập nhẹ hoặc giới hạn.'],
      ['Choose the compound sentence.', 'I felt stressed, so I took a break.', 'Feeling stressed, I took a break.', 'After a short break.', 'Because I felt stressed.', 'Câu ghép có hai mệnh đề độc lập nối bằng so.'],
      ['Choose the correct punctuation.', 'I was tired; however, I kept studying.', 'I was tired, however I kept studying.', 'I was tired however, I kept studying.', 'I was tired; however I kept studying.', 'However là trạng từ nối; dùng dấu chấm phẩy trước và dấu phẩy sau.'],
      ['We can ask the teacher, ___ we can check the instructions.', 'or', 'so', 'but', 'yet', 'Hai phương án lựa chọn nối bằng or.'],
      ['Nam missed the bus, ___ he arrived late.', 'so', 'but', 'or', 'and yet', 'Đến muộn là kết quả của việc lỡ xe buýt.'],
    ], 3),
  },
  4: {
    unit: 4,
    topics: [topic('Câu hỏi Yes/No và Wh-', 'Hỏi để xác nhận đúng/sai hoặc tìm thông tin cụ thể về người, nơi chốn, thời gian, lý do và cách thức.', ['Yes/No: Do/Does/Did + S + V?', 'Wh-: Wh-word + do/does/did + S + V?', 'Với be: Am/Is/Are/Was/Were + S…?', 'Khi who làm chủ ngữ: Who + V…?'], 'Chọn trợ động từ theo thì và chủ ngữ. Sau do/does/did, động từ chính ở dạng nguyên thể. Với who làm chủ ngữ, thường không thêm do/does.', [['Do the Tay have traditional festivals?', 'Người Tày có các lễ hội truyền thống không?'], ['Where do the Thai live?', 'Người Thái sống ở đâu?']], 'Sai: Where does the Tay live? Đúng với chủ ngữ số nhiều: Where do the Tay live?')],
    exercises: exercise([
      ['___ the Tay have traditional festivals?', 'Do', 'Does', 'Did not', 'Are', 'Chủ ngữ the Tay chỉ một cộng đồng số nhiều; hiện tại đơn dùng Do.'],
      ['Where ___ the Thai live?', 'do', 'does', 'are', 'is', 'Câu hỏi Wh- hiện tại đơn với chủ ngữ số nhiều dùng do.'],
      ['___ this stilt house made of wood?', 'Is', 'Do', 'Does', 'Are', 'Câu hỏi với be: Is + chủ ngữ số ít.'],
      ['What ___ the dancers wear at the festival?', 'do', 'does', 'is', 'has', 'Dancers số nhiều; câu hỏi hiện tại đơn dùng do.'],
      ['___ your guide speak English?', 'Does', 'Do', 'Is', 'Are', 'Guide số ít; dùng Does + V nguyên thể.'],
      ['When ___ the festival start last year?', 'did', 'does', 'do', 'was', 'Last year chỉ quá khứ; dùng did + V nguyên thể.'],
      ['___ built the communal house?', 'Who', 'Whom did', 'What did', 'Where', 'Who là chủ ngữ của built, không cần did.'],
      ['Why ___ people wear these costumes?', 'do', 'does', 'are', 'is', 'People số nhiều; dùng do trong câu hỏi hiện tại đơn.'],
      ['Choose the correct question.', 'How do they make this cloth?', 'How they make this cloth?', 'How does they make this cloth?', 'How do they makes this cloth?', 'Câu hỏi Wh- cần do trước chủ ngữ; sau do dùng make.'],
      ['___ these houses on high posts?', 'Are', 'Is', 'Do', 'Does', 'These houses số nhiều; với be dùng Are.'],
    ], 4),
  },
  5: {
    unit: 5,
    topics: [topic('Mạo từ a, an, the và không dùng mạo từ', 'Mạo từ cho biết danh từ được nhắc lần đầu, đã xác định hay mang nghĩa chung.', ['a/an + danh từ đếm được số ít chưa xác định', 'the + danh từ/đối tượng đã xác định', 'Ø + tên bữa ăn, ngôn ngữ và danh từ số nhiều mang nghĩa chung'], 'Dùng an trước âm nguyên âm, không chỉ trước chữ cái nguyên âm. Không dùng a/an với danh từ số nhiều. Tên bữa ăn thường không có mạo từ nếu nói chung.', [['We have dinner at seven.', 'Chúng tôi ăn tối lúc bảy giờ.'], ['The dinner on New Year’s Eve was special.', 'Bữa tối đêm giao thừa ấy rất đặc biệt.']], 'Sai: We eat a dinner every day. Đúng: We eat dinner every day.')],
    exercises: exercise([
      ['We usually have ___ breakfast at home.', 'no article', 'a', 'an', 'the', 'Tên bữa ăn nói chung thường không dùng mạo từ.'],
      ['She brought ___ apple as an offering.', 'an', 'a', 'the', 'no article', 'Apple bắt đầu bằng âm nguyên âm nên dùng an khi chưa xác định.'],
      ['I saw a costume. ___ costume was colourful.', 'The', 'A', 'An', 'no article', 'Nhắc lại đối tượng đã biết nên dùng the.'],
      ['They speak ___ Vietnamese at the festival.', 'no article', 'a', 'an', 'the', 'Tên ngôn ngữ thường không dùng mạo từ.'],
      ['My grandmother told me ___ story about Tet.', 'a', 'an', 'the', 'no article', 'Story là danh từ đếm được số ít nhắc lần đầu, dùng a.'],
      ['___ traditions help families stay connected.', 'no article', 'A', 'An', 'The', 'Danh từ số nhiều mang nghĩa chung có thể không dùng mạo từ.'],
      ['We visited ___ old communal house.', 'an', 'a', 'the', 'no article', 'Old bắt đầu bằng âm nguyên âm nên dùng an.'],
      ['They prepared lunch. ___ lunch was delicious.', 'The', 'A', 'An', 'no article', 'Bữa trưa cụ thể đã nhắc đến nên dùng the.'],
      ['Choose the correct sentence.', 'Children learn table manners at home.', 'Children learn a table manners at home.', 'Children learn an table manners at home.', 'Children learn the table manners at home always.', 'Table manners là danh từ số nhiều mang nghĩa chung; không cần mạo từ.'],
      ['My aunt works in ___ small museum.', 'a', 'an', 'the', 'no article', 'Small bắt đầu bằng âm phụ âm; danh từ số ít chưa xác định dùng a.'],
    ], 5),
  },
  6: {
    unit: 6,
    topics: [
      topic('Thì tương lai đơn', 'Nói về dự đoán, quyết định tại lúc nói hoặc lời hứa liên quan đến tương lai.', ['Khẳng định: S + will + V', 'Phủ định: S + will not/won’t + V', 'Câu hỏi: Will + S + V?'], 'Sau will dùng động từ nguyên thể không to. Dùng will khi chưa có kế hoạch cố định hoặc đưa ra dự đoán.', [['I think online learning will grow.', 'Tôi nghĩ việc học trực tuyến sẽ phát triển.'], ['I will help you with the project.', 'Tôi sẽ giúp bạn làm dự án.']], 'Sai: She will to go. Đúng: She will go.'),
      topic('Điều kiện loại 1', 'Diễn tả điều kiện có thể xảy ra và kết quả tương lai.', ['If + S + present simple, S + will/can/may + V', 'Unless + S + present simple, S + will + V (unless = if…not)'], 'Không dùng will trong mệnh đề if/unless của mẫu cơ bản; sau modal dùng V nguyên thể.', [['If it rains, we will stay home.', 'Nếu trời mưa, chúng tôi sẽ ở nhà.'], ['Unless we leave now, we will be late.', 'Nếu không đi ngay, chúng tôi sẽ muộn.']], 'Sai: If it will rain, we will stay home. Đúng: If it rains, we will stay home.'),
    ],
    exercises: exercise([
      ['I think the town ___ cleaner next year.', 'will become', 'becomes yesterday', 'will to become', 'becoming', 'Dự đoán tương lai dùng will + V.'],
      ['Don’t worry. I ___ you with the task.', 'will help', 'helped', 'will to help', 'helping', 'Lời hứa hoặc quyết định tại lúc nói dùng will + V.'],
      ['___ your family visit the village next month?', 'Will', 'Do', 'Did', 'Is', 'Câu hỏi tương lai đơn bắt đầu bằng Will.'],
      ['She ___ join the trip because she is ill.', 'will not', 'will to not', 'does not will', 'not will', 'Phủ định tương lai đơn: will not + V.'],
      ['If the weather ___ fine, we will cycle.', 'is', 'will be', 'was', 'be', 'Mệnh đề if của điều kiện loại 1 dùng hiện tại đơn.'],
      ['If people cycle more, the air ___ cleaner.', 'will be', 'is yesterday', 'will to be', 'being', 'Mệnh đề kết quả dùng will + V.'],
      ['Unless we leave early, we ___ the bus.', 'will miss', 'missed', 'will to miss', 'missing', 'Unless = if…not; mệnh đề chính dùng will + V.'],
      ['If she ___ online, she can join the lesson.', 'studies', 'will study', 'study', 'studied', 'Chủ ngữ she trong mệnh đề if dùng studies.'],
      ['Choose the correct sentence.', 'If it rains, we will stay home.', 'If it will rain, we stay home.', 'If it rains, we will to stay home.', 'If it rain, we will stay home.', 'Mệnh đề if dùng hiện tại đơn; mệnh đề chính will + V.'],
      ['They ___ forget their tickets tomorrow.', 'will not', 'do not will', 'will not to', 'not will', 'Dạng phủ định đúng là will not + V.'],
    ], 6),
  },
  7: {
    unit: 7,
    topics: [topic('Mệnh đề trạng từ chỉ thời gian', 'Nối hai sự việc và cho biết sự việc nào diễn ra trước, sau, cùng lúc hoặc đến khi nào.', ['Mệnh đề chính + when/while/before/after/as soon as/until + S + V', 'Mệnh đề thời gian + dấu phẩy + mệnh đề chính', 'Tương lai: S + will + V + when/before/after + S + present simple'], 'Trong mệnh đề thời gian chỉ tương lai, dùng hiện tại đơn thay cho will. When = khi; while = trong khi; before = trước khi; after = sau khi; until = cho đến khi.', [['We will plant trees when the rain stops.', 'Chúng tôi sẽ trồng cây khi mưa tạnh.'], ['Before they leave, volunteers will clean the beach.', 'Trước khi rời đi, tình nguyện viên sẽ dọn bãi biển.']], 'Sai: We will leave when the rain will stop. Đúng: We will leave when the rain stops.')],
    exercises: exercise([
      ['We will clean the riverbank when the rain ___.', 'stops', 'will stop', 'stopped', 'stopping', 'Mệnh đề when chỉ tương lai dùng hiện tại đơn: stops.'],
      ['___ we leave, we will switch off the lights.', 'Before', 'Until not', 'During', 'Because of', 'Before diễn tả hành động xảy ra trước khi rời đi.'],
      ['The volunteers will rest after they ___ the trees.', 'plant', 'will plant', 'planted', 'planting', 'Mệnh đề after chỉ tương lai dùng hiện tại đơn.'],
      ['We should stay here until the storm ___.', 'passes', 'will pass', 'passing', 'passed tomorrow', 'Mệnh đề until chỉ tương lai dùng hiện tại đơn.'],
      ['As soon as she ___, we will start the meeting.', 'arrives', 'will arrive', 'arrive', 'arriving', 'As soon as + hiện tại đơn khi nói tương lai.'],
      ['___ we were checking the river, it began to rain.', 'While', 'After', 'Until', 'Before', 'While hợp với hành động đang diễn ra trong quá khứ.'],
      ['They will recycle the bottles before they ___ home.', 'go', 'will go', 'went', 'going', 'Mệnh đề before chỉ tương lai dùng hiện tại đơn.'],
      ['Choose the correct sentence.', 'When the sun rises, we will begin.', 'When the sun will rise, we will begin.', 'When the sun rise, we will begin.', 'When the sun rising, we will begin.', 'Trong mệnh đề when chỉ tương lai dùng hiện tại đơn.'],
      ['The team will call us after the water level ___.', 'falls', 'will fall', 'fall', 'falling', 'Sau after dùng hiện tại đơn cho sự việc tương lai.'],
      ['We will protect the birds ___ they leave the nest.', 'until', 'during', 'because of', 'despite', 'Until = cho đến khi, phù hợp quan hệ thời gian.'],
    ], 7),
  },
  8: {
    unit: 8,
    topics: [
      topic('Trạng từ tần suất', 'Cho biết một hành động xảy ra thường xuyên đến mức nào.', ['S + always/usually/often/sometimes/rarely/never + động từ thường', 'S + be + trạng từ tần suất', 'How often + do/does + S + V?'], 'Trạng từ tần suất thường đứng trước động từ thường nhưng sau be. Never đã mang nghĩa phủ định, không dùng thêm not.', [['I usually shop at the weekend market.', 'Tôi thường mua sắm ở chợ cuối tuần.'], ['The shop is always busy on Fridays.', 'Cửa hàng luôn đông vào thứ Sáu.']], 'Sai: She always is late. Đúng: She is always late.'),
      topic('Hiện tại đơn nói về lịch trình tương lai', 'Diễn tả giờ mở cửa, chuyến xe, sự kiện hoặc lịch trình đã ấn định.', ['S + V(s/es) + thời gian tương lai', 'What time + does + S + V?'], 'Dù có tomorrow hoặc next week, lịch trình cố định vẫn có thể dùng hiện tại đơn.', [['The sale starts tomorrow morning.', 'Đợt giảm giá bắt đầu vào sáng mai.'], ['The bus leaves at 7 a.m. next Monday.', 'Xe buýt khởi hành lúc 7 giờ sáng thứ Hai tới.']], 'Không dùng hiện tại đơn cho mọi dự định cá nhân; cấu trúc này dành cho lịch trình cố định.'),
    ],
    exercises: exercise([
      ['My mother ___ checks the receipt before leaving.', 'usually', 'is usually', 'usual', 'usually is', 'Trạng từ tần suất đứng trước động từ thường checks.'],
      ['The shop is ___ crowded on Saturdays.', 'often', 'is often', 'often is', 'frequency', 'Trạng từ tần suất đứng sau be: is often.'],
      ['Hoa ___ buys things she does not need.', 'rarely', 'is rarely', 'rare', 'rarely is', 'Trước động từ thường buys dùng trạng từ rarely.'],
      ['We ___ compare prices before buying.', 'always', 'are always', 'always are', 'all ways', 'Always đứng trước động từ thường compare.'],
      ['He is ___ late for the morning market.', 'never', 'not never', 'never not', 'no never', 'Never đã mang nghĩa phủ định, đứng sau is.'],
      ['___ do you visit the bookshop?', 'How often', 'How many', 'How much', 'How long ago', 'How often dùng để hỏi tần suất.'],
      ['The sale ___ at nine tomorrow.', 'starts', 'will starting', 'start', 'started', 'Lịch trình cố định dùng hiện tại đơn; sale số ít nên starts.'],
      ['Our train ___ at 6:30 next Monday.', 'leaves', 'leave', 'leaving', 'left', 'Giờ tàu theo lịch dùng hiện tại đơn: leaves.'],
      ['What time ___ the market open tomorrow?', 'does', 'do', 'is', 'has', 'Câu hỏi hiện tại đơn với market số ít dùng does + open.'],
      ['Choose the correct sentence.', 'The shop usually opens at eight.', 'The shop opens usually at eight.', 'The shop is usually opens at eight.', 'The shop usual opens at eight.', 'Usually đứng trước động từ thường opens.'],
    ], 8),
  },
  9: {
    unit: 9,
    topics: [topic('Thì quá khứ tiếp diễn', 'Diễn tả sự việc đang diễn ra tại một thời điểm trong quá khứ hoặc làm nền cho sự việc khác xen vào.', ['Khẳng định: S + was/were + V-ing', 'Phủ định: S + was/were not + V-ing', 'Câu hỏi: Was/Were + S + V-ing?', 'Hành động dài (past continuous) + when + hành động ngắn (past simple)'], 'I/he/she/it dùng was; you/we/they dùng were. Dùng while để nối hai hành động đang diễn ra cùng lúc trong quá khứ.', [['We were having dinner when the flood warning arrived.', 'Chúng tôi đang ăn tối thì cảnh báo lũ tới.'], ['At ten last night, the wind was blowing strongly.', 'Lúc mười giờ tối qua, gió đang thổi mạnh.']], 'Sai: They was sleeping. Đúng: They were sleeping.')],
    exercises: exercise([
      ['At 8 p.m. yesterday, we ___ the emergency kit.', 'were checking', 'checked tomorrow', 'are checking', 'have checked', 'Tại thời điểm xác định trong quá khứ dùng were + V-ing.'],
      ['The ground shook while I ___ a book.', 'was reading', 'read now', 'am reading', 'have read', 'Hành động đang diễn ra trong quá khứ dùng was reading.'],
      ['When the alarm rang, the students ___ in class.', 'were working', 'worked tomorrow', 'are working', 'have worked', 'Were working là hành động dài làm nền cho rang.'],
      ['What ___ you ___ when the storm began?', 'were / doing', 'did / doing', 'are / done', 'have / do', 'Câu hỏi quá khứ tiếp diễn: were + you + V-ing.'],
      ['The rescue workers ___ along the river all morning.', 'were searching', 'are searching tomorrow', 'have searching', 'search', 'All morning trong bối cảnh quá khứ nhấn mạnh hành động kéo dài.'],
      ['My sister ___ when the warning message came.', 'was sleeping', 'were sleeping', 'is sleeping', 'has slept', 'Sister số ít dùng was + V-ing.'],
      ['While Dad was driving, Mum ___ the weather report.', 'was reading', 'reads', 'has read', 'is reading', 'Hai hành động song song trong quá khứ dùng quá khứ tiếp diễn.'],
      ['The children ___ outside at 9 o’clock last night.', 'were not playing', 'did not playing', 'are not play', 'not were playing', 'Phủ định quá khứ tiếp diễn: were not + V-ing.'],
      ['Choose the correct sentence.', 'We were leaving when it started to rain.', 'We was leaving when it started to rain.', 'We were leave when it started to rain.', 'We leaving when it started to rain.', 'We số nhiều dùng were leaving.'],
      ['___ Lan watching the news at seven yesterday?', 'Was', 'Were', 'Did', 'Has', 'Câu hỏi quá khứ tiếp diễn với Lan số ít bắt đầu bằng Was.'],
    ], 9),
  },
  10: {
    unit: 10,
    topics: [
      topic('Giới từ chỉ thời gian và địa điểm', 'At, on, in giúp xác định thời gian hoặc vị trí ở các mức độ cụ thể khác nhau.', ['at + giờ/điểm cụ thể: at 8 a.m., at the station', 'on + ngày/bề mặt: on Monday, on the screen', 'in + tháng/năm/khoảng không gian: in June, in the room'], 'Dùng at với giờ cụ thể; on với ngày; in với tháng, năm. Với địa điểm, chú ý nghĩa của điểm, bề mặt hoặc không gian bao quanh.', [['The video call starts at eight on Friday.', 'Cuộc gọi video bắt đầu lúc tám giờ vào thứ Sáu.'], ['The message appeared on the screen.', 'Tin nhắn xuất hiện trên màn hình.']], 'Sai: in Monday, on 8 a.m. Đúng: on Monday, at 8 a.m.'),
      topic('Đại từ sở hữu', 'Thay cho tính từ sở hữu cộng danh từ khi danh từ đã rõ.', ['mine = my + noun; yours = your + noun', 'his, hers, ours, theirs đứng độc lập', 'This tablet is mine. = This is my tablet.'], 'Không đặt danh từ ngay sau mine, yours, hers, ours hoặc theirs.', [['This headset is mine.', 'Chiếc tai nghe này là của tôi.'], ['The blue tablet is theirs.', 'Chiếc máy tính bảng màu xanh là của họ.']], 'Sai: mine headset. Đúng: my headset hoặc the headset is mine.'),
    ],
    exercises: exercise([
      ['The video conference begins ___ 8 a.m.', 'at', 'on', 'in', 'by on', 'Giờ cụ thể dùng at.'],
      ['Our class will meet online ___ Monday.', 'on', 'at', 'in', 'by in', 'Ngày trong tuần dùng on.'],
      ['The meeting takes place ___ September.', 'in', 'on', 'at', 'to', 'Tháng dùng in.'],
      ['The emoji appeared ___ the screen.', 'on', 'in', 'at', 'under at', 'Trên bề mặt màn hình dùng on.'],
      ['The students are ___ the computer room.', 'in', 'on', 'at on', 'to in', 'Không gian bao quanh dùng in the room.'],
      ['This microphone belongs to me. It is ___.', 'mine', 'my', 'me', 'I', 'Đại từ sở hữu mine đứng độc lập, không cần danh từ sau.'],
      ['The blue tablet belongs to Hoa. It is ___.', 'hers', 'her', 'she', 'their', 'Hers là đại từ sở hữu chỉ của cô ấy.'],
      ['These headphones belong to us. They are ___.', 'ours', 'our', 'we', 'us', 'Ours là đại từ sở hữu chỉ của chúng tôi.'],
      ['Choose the correct sentence.', 'This webcam is theirs.', 'This webcam is their.', 'This is theirs webcam.', 'This webcam theirs.', 'Theirs đứng độc lập sau be; their phải đi với danh từ.'],
      ['That is ___ laptop, not mine.', 'your', 'yours', 'you', 'yourself', 'Trước danh từ laptop dùng tính từ sở hữu your.'],
    ], 10),
  },
  11: {
    unit: 11,
    topics: [topic('Tường thuật câu trần thuật', 'Kể lại lời ai đó nói mà không đặt nguyên văn trong dấu ngoặc kép.', ['S + said (that) + S + V đã lùi thì', 'S + told + người nghe + (that) + S + V đã lùi thì', 'am/is → was; are → were; will → would; can → could'], 'Khi động từ tường thuật ở quá khứ, thường lùi thì và đổi đại từ, trạng từ thời gian theo góc nhìn mới. Told phải có tân ngữ chỉ người.', [['Lan said, “I can fix it.” → Lan said that she could fix it.', 'Lan nói rằng cô ấy có thể sửa nó.'], ['Dad said, “The robot is ready.” → Dad said that the robot was ready.', 'Bố nói rằng rô-bốt đã sẵn sàng.']], 'Sai: Lan told that she was ready. Đúng: Lan said that she was ready hoặc Lan told me that she was ready.')],
    exercises: exercise([
      ['“I am busy,” Lan said. → Lan said she ___ busy.', 'was', 'is always', 'were', 'be', 'Am lùi thành was khi tường thuật với said ở quá khứ.'],
      ['“We are ready,” they said. → They said they ___ ready.', 'were', 'was', 'are tomorrow', 'be', 'Are lùi thành were.'],
      ['“I can help,” Minh said. → Minh said he ___ help.', 'could', 'can to', 'will can', 'should to', 'Can lùi thành could.'],
      ['“We will test it,” they said. → They said they ___ test it.', 'would', 'will to', 'would to', 'were', 'Will lùi thành would.'],
      ['The scientist ___ that the result was surprising.', 'said', 'told', 'spoke me', 'said me', 'Said có thể đi trực tiếp với that-clause; told cần người nghe.'],
      ['The teacher ___ us that the robot was safe.', 'told', 'said', 'spoke', 'talked', 'Told + người nghe + that-clause là cấu trúc đúng.'],
      ['“My tablet is new,” she said. → She said that ___ tablet was new.', 'her', 'my', 'their', 'our', 'Đổi my thành her theo người được tường thuật.'],
      ['“I like science,” Hoa said. → Hoa said she ___ science.', 'liked', 'likes now', 'liking', 'has like', 'Hiện tại đơn lùi thành quá khứ đơn khi tường thuật.'],
      ['Choose the correct sentence.', 'He told me that he was tired.', 'He told that he was tired.', 'He said me that he was tired.', 'He told me that he is tired yesterday.', 'Told phải có tân ngữ người; be lùi thành was.'],
      ['“I have a plan,” Nam said. → Nam said he ___ a plan.', 'had', 'has', 'have', 'having', 'Have (hiện tại) lùi thành had trong câu tường thuật.'],
    ], 11),
  },
  12: {
    unit: 12,
    topics: [topic('Tường thuật câu hỏi', 'Kể lại một câu hỏi Yes/No hoặc Wh- mà không giữ trật tự đảo ngữ của câu hỏi trực tiếp.', ['Yes/No: S + asked + if/whether + S + V', 'Wh-: S + asked + who/what/where/when/why/how + S + V', 'Không dùng dấu hỏi sau câu tường thuật hoàn chỉnh'], 'Giữ từ để hỏi ở câu Wh-. Với câu Yes/No, thêm if hoặc whether. Khi động từ tường thuật ở quá khứ, thường lùi thì và đổi đại từ/thời gian khi cần.', [['“Is Mars cold?” he asked. → He asked whether Mars was cold.', 'Cậu ấy hỏi liệu Sao Hỏa có lạnh không.'], ['“Where do they live?” she asked. → She asked where they lived.', 'Cô ấy hỏi họ sống ở đâu.']], 'Sai: She asked where did they live. Đúng: She asked where they lived.')],
    exercises: exercise([
      ['“Is Mars cold?” → He asked ___ Mars was cold.', 'whether', 'what', 'where', 'why', 'Câu hỏi Yes/No dùng whether hoặc if.'],
      ['“Do aliens exist?” → She asked ___ aliens existed.', 'if', 'who', 'where', 'when', 'Câu hỏi Yes/No tường thuật dùng if/whether.'],
      ['“Where do they live?” → He asked where they ___.', 'lived', 'did live', 'live now', 'living', 'Câu hỏi tường thuật dùng trật tự khẳng định và lùi thì.'],
      ['“What can the robot do?” → She asked what the robot ___ do.', 'could', 'can to', 'did can', 'would can', 'Can lùi thành could; không đảo ngữ.'],
      ['“When will it land?” → He asked when it ___ land.', 'would', 'will to', 'did will', 'was will', 'Will lùi thành would.'],
      ['“Are they ready?” → Dad asked if they ___ ready.', 'were', 'are tomorrow', 'was', 'be', 'Are lùi thành were sau asked ở quá khứ.'],
      ['“Why is the sky red?” → She asked why the sky ___ red.', 'was', 'did be', 'is tomorrow', 'were', 'Câu hỏi gián tiếp dùng trật tự khẳng định và is lùi thành was.'],
      ['Choose the correct sentence.', 'He asked where I lived.', 'He asked where did I live.', 'He asked where I did live?', 'He asked where lived I.', 'Sau asked + wh-word dùng trật tự chủ ngữ–động từ.'],
      ['“Have they found water?” → She asked if they ___ water.', 'had found', 'have find', 'did found', 'were found', 'Hiện tại hoàn thành thường lùi thành quá khứ hoàn thành.'],
      ['“How does it work?” → He asked how it ___.', 'worked', 'did work', 'works tomorrow', 'working', 'Câu hỏi gián tiếp không đảo trợ động từ; does work lùi thành worked.'],
    ], 12),
  },
};
