import type { Exam, Question } from './exams';

export type VocabularyEntry = { word: string; ipa: string; meaning: string; example: string };
export type PronunciationEntry = {
  title: string;
  guidance: string;
  examples: string;
  options: [string, string, string, string];
  underlines?: [string, string, string, string];
  answer: number;
  explanation: string;
  prompt?: string;
};
export type UnitEnrichment = { vocabulary: [VocabularyEntry, VocabularyEntry, VocabularyEntry, VocabularyEntry]; pronunciation: PronunciationEntry };

const v = (word: string, ipa: string, meaning: string, example: string): VocabularyEntry => ({ word, ipa, meaning, example });
const p = (title: string, guidance: string, examples: string, options: PronunciationEntry['options'], underlines: PronunciationEntry['underlines'], answer: number, explanation: string, prompt?: string): PronunciationEntry => ({ title, guidance, examples, options, underlines, answer, explanation, prompt });

// Original examples and questions aligned to the public Unit topic outlines; no source exercises are reproduced.
export const unitEnrichment: Record<8 | 9 | 10, Record<number, UnitEnrichment>> = {
  8: {
    1: { vocabulary: [v('leisure', '/ˈleʒə(r)/', 'thời gian rảnh', 'I read comics in my leisure time.'), v('origami', '/ˌɒrɪˈɡɑːmi/', 'nghệ thuật gấp giấy', 'We made origami birds after class.'), v('hang out', '/hæŋ aʊt/', 'đi chơi, dành thời gian cùng bạn bè', 'My friends hang out at the park.'), v('DIY', '/ˌdiː aɪ ˈwaɪ/', 'tự làm hoặc sửa đồ', 'Dad enjoys simple DIY projects.')], pronunciation: p('/ʊ/ và /uː/', 'Âm /ʊ/ ngắn, môi tròn nhẹ; /uː/ dài hơn và môi tròn rõ hơn.', 'book /bʊk/ · cook /kʊk/ · moon /muːn/', ['book', 'cook', 'look', 'moon'], ['oo', 'oo', 'oo', 'oo'], 3, '“Moon” có /uː/ dài; ba từ còn lại có /ʊ/ ngắn.') },
    2: { vocabulary: [v('harvest', '/ˈhɑːvɪst/', 'thu hoạch', 'Neighbours help each other harvest rice.'), v('orchard', '/ˈɔːtʃəd/', 'vườn cây ăn quả', 'The family grows oranges in an orchard.'), v('herd', '/hɜːd/', 'chăn dắt một đàn vật nuôi', 'She helps herd the cattle home.'), v('picturesque', '/ˌpɪktʃəˈresk/', 'đẹp như tranh', 'The riverside village is picturesque.')], pronunciation: p('/ə/ và /ɪ/', 'Âm /ə/ là âm rất nhẹ, thường nằm ở âm tiết không nhấn; /ɪ/ ngắn nhưng rõ hơn.', 'about /əˈbaʊt/ · away /əˈweɪ/ · village /ˈvɪlɪdʒ/', ['about', 'away', 'around', 'village'], ['a', 'a', 'a', 'i'], 3, 'Chữ gạch dưới trong “village” đọc /ɪ/; ba từ kia bắt đầu bằng /ə/.') },
    3: { vocabulary: [v('pressure', '/ˈpreʃə(r)/', 'áp lực', 'Too many tasks can create pressure.'), v('bullying', '/ˈbʊliɪŋ/', 'việc bắt nạt', 'Our class speaks up against bullying.'), v('deadline', '/ˈdedlaɪn/', 'hạn cuối', 'I wrote the project deadline in my diary.'), v('concentrate', '/ˈkɒnsntreɪt/', 'tập trung', 'A quiet desk helps me concentrate.')], pronunciation: p('/ʊə/ và /ɔɪ/', 'Âm /ɔɪ/ chuyển từ /ɔ/ sang /ɪ/ như trong boy; /ʊə/ bắt đầu bằng /ʊ/ rồi lướt sang /ə/ trong một số giọng Anh.', 'boy /bɔɪ/ · choice /tʃɔɪs/ · cure /kjʊə(r)/', ['tour', 'cure', 'pure', 'choice'], ['our', 'ure', 'ure', 'oi'], 3, '“Choice” có âm /ɔɪ/; các từ còn lại không có âm này. Cách đọc /ʊə/ có thể khác nhau giữa các giọng Anh.', 'Which word contains the /ɔɪ/ sound?') },
    4: { vocabulary: [v('ethnic group', '/ˈeθnɪk ɡruːp/', 'nhóm dân tộc', 'Each ethnic group has its own traditions.'), v('stilt house', '/stɪlt haʊs/', 'nhà sàn', 'The family welcomed us into their stilt house.'), v('costume', '/ˈkɒstjuːm/', 'trang phục', 'The performers wore colourful costumes.'), v('folk dance', '/fəʊk dɑːns/', 'điệu múa dân gian', 'We learnt a folk dance at the festival.')], pronunciation: p('/k/ và /ɡ/', '/k/ là âm vô thanh, không rung cổ; /ɡ/ là âm hữu thanh, có rung cổ.', 'kite /kaɪt/ · school /skuːl/ · garden /ˈɡɑːdn/', ['kite', 'kitchen', 'school', 'garden'], ['k', 'k', 'ch', 'g'], 3, '“Garden” bắt đầu bằng /ɡ/ hữu thanh; ba từ còn lại có /k/.') },
    5: { vocabulary: [v('custom', '/ˈkʌstəm/', 'phong tục', 'Taking off shoes is a custom in many homes.'), v('tradition', '/trəˈdɪʃn/', 'truyền thống', 'Our family keeps this tradition every Tet.'), v('offering', '/ˈɒfərɪŋ/', 'lễ vật', 'They placed fruit on the table as an offering.'), v('table manners', '/ˈteɪbl ˌmænəz/', 'phép lịch sự trên bàn ăn', 'Children learn table manners from adults.')], pronunciation: p('/n/ và /ŋ/', 'Với /n/, đầu lưỡi chạm lợi trên; với /ŋ/, phần sau lưỡi chạm ngạc mềm.', 'name /neɪm/ · nine /naɪn/ · singing /ˈsɪŋɪŋ/', ['name', 'nine', 'need', 'singing'], ['n', 'n', 'n', 'ng'], 3, 'Cụm “ng” trong “singing” đọc /ŋ/; các chữ n gạch dưới đọc /n/.') },
    6: { vocabulary: [v('lifestyle', '/ˈlaɪfstaɪl/', 'lối sống', 'Cycling is part of her healthy lifestyle.'), v('habit', '/ˈhæbɪt/', 'thói quen', 'Drinking water is a useful habit.'), v('generation', '/ˌdʒenəˈreɪʃn/', 'thế hệ', 'Each generation uses technology differently.'), v('street food', '/striːt fuːd/', 'món ăn đường phố', 'The market has delicious street food.')], pronunciation: p('/br/ và /pr/', 'Bật /b/ rồi chuyển ngay sang /r/ trong /br/; /pr/ bắt đầu bằng /p/ bật hơi.', 'bread /bred/ · bright /braɪt/ · prize /praɪz/', ['bread', 'bright', 'broom', 'prize'], ['br', 'br', 'br', 'pr'], 3, '“Prize” bắt đầu bằng /pr/; ba từ còn lại bắt đầu bằng /br/.') },
    7: { vocabulary: [v('habitat', '/ˈhæbɪtæt/', 'môi trường sống', 'The wetland is a bird habitat.'), v('endangered', '/ɪnˈdeɪndʒəd/', 'có nguy cơ tuyệt chủng', 'The turtle is an endangered animal.'), v('biodiversity', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'đa dạng sinh học', 'Forests support biodiversity.'), v('conservation', '/ˌkɒnsəˈveɪʃn/', 'sự bảo tồn', 'Our club supports forest conservation.')], pronunciation: p('/bl/ và /kl/', 'Giữ hai phụ âm sát nhau, không chèn thêm nguyên âm vào giữa.', 'blue /bluː/ · black /blæk/ · clean /kliːn/', ['blue', 'black', 'blanket', 'clean'], ['bl', 'bl', 'bl', 'cl'], 3, '“Clean” bắt đầu bằng /kl/; ba từ kia bắt đầu bằng /bl/.') },
    8: { vocabulary: [v('bargain', '/ˈbɑːɡən/', 'món hàng giá hời', 'This backpack was a bargain.'), v('receipt', '/rɪˈsiːt/', 'hóa đơn', 'Keep the receipt after you pay.'), v('discount', '/ˈdɪskaʊnt/', 'mức giảm giá', 'Students receive a small discount.'), v('customer', '/ˈkʌstəmə(r)/', 'khách hàng', 'The customer asked about the price.')], pronunciation: p('/sp/ và /st/', '/sp/ chuyển từ /s/ sang /p/; /st/ chuyển từ /s/ sang /t/.', 'sport /spɔːt/ · speak /spiːk/ · store /stɔː(r)/', ['sport', 'speak', 'spend', 'store'], ['sp', 'sp', 'sp', 'st'], 3, '“Store” bắt đầu bằng /st/; ba từ còn lại bắt đầu bằng /sp/.') },
    9: { vocabulary: [v('earthquake', '/ˈɜːθkweɪk/', 'động đất', 'The earthquake damaged the road.'), v('landslide', '/ˈlændslaɪd/', 'sạt lở đất', 'Heavy rain caused a landslide.'), v('evacuate', '/ɪˈvækjueɪt/', 'sơ tán', 'The team helped evacuate the village.'), v('warning', '/ˈwɔːnɪŋ/', 'lời cảnh báo', 'We received a storm warning.')], pronunciation: p('Trọng âm từ tận cùng -al và -ous', 'Không đoán trọng âm chỉ từ đuôi; hãy đọc cả từ và đánh dấu âm tiết nhấn bằng dấu ˈ trong IPA.', 'natural /ˈnætʃərəl/ · dangerous /ˈdeɪndʒərəs/ · delicious /dɪˈlɪʃəs/', ['natural', 'dangerous', 'musical', 'delicious'], undefined, 3, '“Delicious” nhấn âm tiết thứ hai; natural, dangerous và musical nhấn âm tiết thứ nhất.', 'Which word has a different stress pattern?') },
    10: { vocabulary: [v('hologram', '/ˈhɒləɡræm/', 'hình ảnh ba chiều tạo bằng ánh sáng', 'The speaker appeared as a hologram.'), v('emoji', '/ɪˈməʊdʒi/', 'biểu tượng cảm xúc', 'She added an emoji to the message.'), v('telepathy', '/təˈlepəθi/', 'thần giao cách cảm', 'Telepathy is common in science fiction.'), v('video conference', '/ˈvɪdiəʊ ˈkɒnfərəns/', 'cuộc họp qua video', 'Our class joined a video conference.')], pronunciation: p('Trọng âm đuôi -ese và -ee', 'Nhiều từ kết thúc bằng -ese hoặc -ee nhấn vào âm tiết cuối.', 'Japanese /ˌdʒæpəˈniːz/ · employee /ɪmˌplɔɪˈiː/ · cinema /ˈsɪnəmə/', ['Japanese', 'employee', 'volunteer', 'cinema'], undefined, 3, '“Cinema” nhấn âm tiết đầu; ba từ kia nhấn ở cuối.', 'Which word has a different stress pattern?') },
    11: { vocabulary: [v('invention', '/ɪnˈvenʃn/', 'phát minh', 'The invention saves water.'), v('laboratory', '/ləˈbɒrətri/', 'phòng thí nghiệm', 'The team works in a laboratory.'), v('experiment', '/ɪkˈsperɪmənt/', 'thí nghiệm', 'We planned a simple experiment.'), v('digital', '/ˈdɪdʒɪtl/', 'thuộc công nghệ số', 'The museum offers a digital guide.')], pronunciation: p('/s/ và /ʃ/ — luyện phát âm bổ trợ', '/s/ tạo luồng hơi thẳng qua răng; /ʃ/ đẩy môi tròn nhẹ và lưỡi lùi hơn.', 'science /ˈsaɪəns/ · see /siː/ · ship /ʃɪp/', ['science', 'see', 'sun', 'ship'], ['s', 's', 's', 'sh'], 3, '“Ship” bắt đầu bằng /ʃ/; ba từ kia bắt đầu bằng /s/.') },
    12: { vocabulary: [v('galaxy', '/ˈɡæləksi/', 'thiên hà', 'Our galaxy contains many stars.'), v('gravity', '/ˈɡrævəti/', 'trọng lực', 'Gravity keeps us on the ground.'), v('spacecraft', '/ˈspeɪskrɑːft/', 'tàu vũ trụ', 'The spacecraft sent back pictures.'), v('habitable', '/ˈhæbɪtəbl/', 'có thể sinh sống', 'Scientists seek habitable planets.')], pronunciation: p('/t/ và /θ/ — luyện phát âm bổ trợ', 'Với /θ/, đặt đầu lưỡi nhẹ giữa hai hàm răng và thổi hơi; /t/ chặn rồi bật hơi ở lợi trên.', 'ten /ten/ · time /taɪm/ · think /θɪŋk/', ['ten', 'time', 'team', 'think'], ['t', 't', 't', 'th'], 3, '“Think” bắt đầu bằng /θ/; ba từ còn lại bắt đầu bằng /t/.') },
  },
  9: {
    1: { vocabulary: [v('artisan', '/ˌɑːtɪˈzæn/', 'người thợ thủ công', 'An artisan taught us to shape clay.'), v('handicraft', '/ˈhændikrɑːft/', 'đồ thủ công', 'The market sells local handicrafts.'), v('preserve', '/prɪˈzɜːv/', 'gìn giữ', 'We hope to preserve this old craft.'), v('speciality', '/ˌspeʃiˈæləti/', 'đặc sản', 'Rice cakes are a local speciality.')], pronunciation: p('/æ/, /ɑː/ và /e/', '/æ/ mở miệng rộng; /ɑː/ là âm dài ở phía sau; /e/ ngắn và miệng mở vừa.', 'cat /kæt/ · park /pɑːk/ · bed /bed/', ['cat', 'map', 'hand', 'park'], ['a', 'a', 'a', 'ar'], 3, '“Park” có /ɑː/ dài; ba từ còn lại có /æ/.') },
    2: { vocabulary: [v('bustling', '/ˈbʌslɪŋ/', 'nhộn nhịp', 'The downtown market is bustling.'), v('congested', '/kənˈdʒestɪd/', 'ùn tắc', 'The road is congested at five.'), v('pedestrian', '/pəˈdestriən/', 'người đi bộ', 'Pedestrians use the new crossing.'), v('amenity', '/əˈmiːnəti/', 'tiện ích', 'A nearby library is a useful amenity.')], pronunciation: p('/aʊ/, /əʊ/ và /eə/', 'Chú ý đường lướt của nguyên âm đôi, không đọc thành hai âm tách rời.', 'town /taʊn/ · road /rəʊd/ · square /skweə(r)/', ['town', 'brown', 'crowd', 'road'], ['ow', 'ow', 'ow', 'oa'], 3, '“Road” có /əʊ/; ba từ kia có /aʊ/.') },
    3: { vocabulary: [v('due date', '/ˈdjuː deɪt/', 'ngày đến hạn', 'Write the due date on your calendar.'), v('optimistic', '/ˌɒptɪˈmɪstɪk/', 'lạc quan', 'She remains optimistic about the test.'), v('distraction', '/dɪˈstrækʃn/', 'điều gây xao nhãng', 'Turn off your phone to avoid distractions.'), v('stressed out', '/strest aʊt/', 'căng thẳng quá mức', 'He felt stressed out before the exam.')], pronunciation: p('/h/ và /r/', '/h/ chỉ là luồng hơi; /r/ dùng lưỡi cong nhẹ, không rung mạnh.', 'healthy /ˈhelθi/ · habit /ˈhæbɪt/ · ready /ˈredi/', ['healthy', 'habit', 'homework', 'ready'], ['h', 'h', 'h', 'r'], 3, '“Ready” bắt đầu bằng /r/; ba từ kia bắt đầu bằng /h/.') },
    4: { vocabulary: [v('heritage', '/ˈherɪtɪdʒ/', 'di sản', 'The town protects its cultural heritage.'), v('monument', '/ˈmɒnjumənt/', 'công trình tưởng niệm', 'We visited a stone monument.'), v('preserve', '/prɪˈzɜːv/', 'bảo tồn', 'The museum preserves old photographs.'), v('generation', '/ˌdʒenəˈreɪʃn/', 'thế hệ', 'Stories pass from one generation to another.')], pronunciation: p('/m/ và /l/', 'Với /m/, khép môi và đưa hơi qua mũi; với /l/, đầu lưỡi chạm lợi trên.', 'museum /mjuˈziːəm/ · memory /ˈmeməri/ · landscape /ˈlændskeɪp/', ['museum', 'memory', 'moment', 'landscape'], ['m', 'm', 'm', 'l'], 3, '“Landscape” bắt đầu bằng /l/; ba từ còn lại bắt đầu bằng /m/.') },
    5: { vocabulary: [v('memorable', '/ˈmemərəbl/', 'đáng nhớ', 'The camping trip was memorable.'), v('embarrassed', '/ɪmˈbærəst/', 'xấu hổ', 'I felt embarrassed when I forgot my speech.'), v('experience', '/ɪkˈspɪəriəns/', 'trải nghiệm', 'The trip was a new experience.'), v('by rote', '/baɪ rəʊt/', 'theo lối học thuộc lòng', 'Do not learn every sentence by rote.')], pronunciation: p('/j/ và /w/', '/j/ là âm đầu của yes; /w/ bắt đầu bằng môi tròn như trong we.', 'yes /jes/ · young /jʌŋ/ · water /ˈwɔːtə(r)/', ['yes', 'young', 'yellow', 'water'], ['y', 'y', 'y', 'w'], 3, '“Water” bắt đầu bằng /w/; ba từ kia bắt đầu bằng /j/.') },
    6: { vocabulary: [v('generation gap', '/ˌdʒenəˈreɪʃn ɡæp/', 'khoảng cách thế hệ', 'Talking openly can narrow the generation gap.'), v('privacy', '/ˈprɪvəsi/', 'quyền riêng tư', 'Everyone needs some privacy.'), v('independent', '/ˌɪndɪˈpendənt/', 'độc lập', 'She became more independent this year.'), v('family values', '/ˈfæməli ˈvæljuːz/', 'giá trị gia đình', 'They discuss family values at dinner.')], pronunciation: p('/fl/ và /fr/', 'Hai cụm đều bắt đầu bằng /f/; âm thứ hai là /l/ hoặc /r/, không chèn nguyên âm.', 'flower /ˈflaʊə(r)/ · floor /flɔː(r)/ · fresh /freʃ/', ['flower', 'floor', 'flight', 'fresh'], ['fl', 'fl', 'fl', 'fr'], 3, '“Fresh” bắt đầu bằng /fr/; ba từ kia bắt đầu bằng /fl/.') },
  },
  10: {
    1: { vocabulary: [v('chore', '/tʃɔː(r)/', 'việc nhà', 'We share chores every weekend.'), v('breadwinner', '/ˈbredwɪnə(r)/', 'người kiếm thu nhập chính', 'Both parents are breadwinners.'), v('homemaker', '/ˈhəʊmmeɪkə(r)/', 'người chăm sóc, quản lý nhà', 'A homemaker does valuable work.'), v('family bond', '/ˈfæməli bɒnd/', 'sự gắn kết gia đình', 'Shared meals strengthen family bonds.')], pronunciation: p('/br/, /kr/ và /tr/', 'Đọc hai phụ âm trong mỗi cụm sát nhau, không thêm âm /ə/ ở giữa.', 'bread /bred/ · cream /kriːm/ · tree /triː/', ['bread', 'brown', 'bright', 'cream'], ['br', 'br', 'br', 'cr'], 3, '“Cream” bắt đầu bằng /kr/; ba từ còn lại bắt đầu bằng /br/.') },
    2: { vocabulary: [v('carbon footprint', '/ˌkɑːbən ˈfʊtprɪnt/', 'lượng khí thải do hoạt động tạo ra', 'Cycling can reduce your carbon footprint.'), v('renewable', '/rɪˈnjuːəbl/', 'có thể tái tạo', 'Sunlight is a renewable energy source.'), v('recycle', '/ˌriːˈsaɪkl/', 'tái chế', 'We recycle paper at school.'), v('habitat', '/ˈhæbɪtæt/', 'môi trường sống', 'The forest is a natural habitat.')], pronunciation: p('/kl/, /pl/, /gr/ và /pr/', 'Tập chuyển thẳng từ phụ âm đầu sang âm tiếp theo, đặc biệt không thêm một nguyên âm đệm.', 'clean /kliːn/ · plant /plɑːnt/ · green /ɡriːn/ · prize /praɪz/', ['clean', 'climb', 'clap', 'plant'], ['cl', 'cl', 'cl', 'pl'], 3, '“Plant” bắt đầu bằng /pl/; ba từ còn lại bắt đầu bằng /kl/.') },
    3: { vocabulary: [v('melody', '/ˈmelədi/', 'giai điệu', 'I remember the song’s melody.'), v('perform', '/pəˈfɔːm/', 'biểu diễn', 'The band will perform tonight.'), v('audience', '/ˈɔːdiəns/', 'khán giả', 'The audience applauded loudly.'), v('talent', '/ˈtælənt/', 'tài năng', 'The contest highlights young talent.')], pronunciation: p('Trọng âm từ hai âm tiết', 'Nhiều danh từ hai âm tiết nhấn âm đầu, nhiều động từ nhấn âm sau; đây là xu hướng, không phải quy tắc tuyệt đối.', 'music /ˈmjuːzɪk/ · singer /ˈsɪŋə(r)/ · perform /pəˈfɔːm/', ['music', 'singer', 'concert', 'perform'], undefined, 3, '“Perform” nhấn âm tiết thứ hai; ba danh từ còn lại nhấn âm đầu.', 'Which word has a different stress pattern?') },
    4: { vocabulary: [v('volunteer', '/ˌvɒlənˈtɪə(r)/', 'tình nguyện viên', 'A volunteer helped at the library.'), v('donate', '/dəʊˈneɪt/', 'quyên góp', 'We donate books to the centre.'), v('charity', '/ˈtʃærəti/', 'tổ chức hoặc hoạt động từ thiện', 'The charity supports local children.'), v('benefit', '/ˈbenɪfɪt/', 'lợi ích', 'The project brings a benefit to everyone.')], pronunciation: p('Trọng âm ở từ hai âm tiết cùng cách viết', 'Một số từ đổi trọng âm theo loại từ: danh từ RECORD nhấn âm đầu; động từ reCORD nhấn âm sau.', 'a record /ˈrekɔːd/ · to record /rɪˈkɔːd/', ['record (noun)', 'present (noun)', 'export (noun)', 'record (verb)'], undefined, 3, '“Record” là động từ nhấn âm tiết thứ hai; ba danh từ còn lại nhấn âm đầu.', 'Which option is stressed on the second syllable?') },
    5: { vocabulary: [v('invention', '/ɪnˈvenʃn/', 'phát minh', 'This invention saves time.'), v('device', '/dɪˈvaɪs/', 'thiết bị', 'The device measures temperature.'), v('portable', '/ˈpɔːtəbl/', 'có thể mang theo', 'She uses a portable charger.'), v('innovation', '/ˌɪnəˈveɪʃn/', 'sự đổi mới', 'Innovation can solve everyday problems.')], pronunciation: p('Trọng âm danh từ ba âm tiết', 'Đếm âm tiết và nghe âm nào nổi bật hơn; danh từ ba âm tiết không phải lúc nào cũng nhấn cùng một vị trí.', 'instrument /ˈɪnstrəmənt/ · company /ˈkʌmpəni/ · inventor /ɪnˈventə(r)/', ['instrument', 'company', 'benefit', 'inventor'], undefined, 3, '“Inventor” nhấn âm tiết thứ hai; ba danh từ kia nhấn âm đầu.', 'Which word has a different stress pattern?') },
    6: { vocabulary: [v('equality', '/ɪˈkwɒləti/', 'sự bình đẳng', 'Equality matters in every workplace.'), v('opportunity', '/ˌɒpəˈtjuːnəti/', 'cơ hội', 'Everyone deserves an opportunity to learn.'), v('discrimination', '/dɪˌskrɪmɪˈneɪʃn/', 'sự phân biệt đối xử', 'The policy aims to prevent discrimination.'), v('confident', '/ˈkɒnfɪdənt/', 'tự tin', 'The speaker sounded confident.')], pronunciation: p('Trọng âm tính từ và động từ ba âm tiết', 'Đánh dấu trọng âm trong phiên âm và kiểm tra từng từ; cùng ba âm tiết vẫn có thể nhấn khác nhau.', 'positive /ˈpɒzətɪv/ · confident /ˈkɒnfɪdənt/ · successful /səkˈsesfəl/', ['positive', 'confident', 'popular', 'successful'], undefined, 3, '“Successful” nhấn âm tiết thứ hai; ba tính từ còn lại nhấn âm đầu.', 'Which word has a different stress pattern?') },
  },
};

export function enrichUnitExam(exam: Exam, grade: 8 | 9 | 10): Exam {
  if (exam.menuGroup !== 'unit') return exam;
  const unit = grade === 8 ? exam.id - 6 : grade === 9 ? exam.id - 100 : exam.id;
  const enrichment = unitEnrichment[grade][unit];
  if (!enrichment) return exam;

  const vocabularyQuestions: Question[] = enrichment.vocabulary.map((entry, index) => {
    const alternatives = enrichment.vocabulary.filter((_, otherIndex) => otherIndex !== index).map((item) => item.word);
    const answer = index % 4;
    const options = [...alternatives];
    options.splice(answer, 0, entry.word);
    return {
      id: exam.questions.length + index + 1,
      section: 'Language Focus',
      prompt: entry.example.toLowerCase().includes(entry.word.toLowerCase())
        ? entry.example.replace(new RegExp(entry.word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'), '___')
        : `Which unit word best completes this example? ${entry.example}`,
      options,
      answer,
      explanation: `“${entry.word}” ${entry.ipa} nghĩa là “${entry.meaning}”. Ví dụ: ${entry.example}`,
      origin: 'unit-enrichment',
    };
  });

  const sound = enrichment.pronunciation;
  const soundQuestion: Question = {
    id: exam.questions.length + vocabularyQuestions.length + 1,
    section: 'Language Focus',
    prompt: sound.prompt ?? 'Choose the word whose underlined part is pronounced differently.',
    options: [...sound.options],
    underlines: sound.underlines ? [...sound.underlines] : undefined,
    answer: sound.answer,
    explanation: sound.explanation,
    origin: 'unit-enrichment',
  };

  return {
    ...exam,
    theme: exam.theme.replace(/\d+ câu/, `${exam.questions.length + vocabularyQuestions.length + 1} câu`),
    sourceNote: grade === 9
      ? 'Từ vựng, ngữ pháp và phát âm được biên soạn mới theo chủ điểm của Tiếng Anh 9 Global Success; không gồm phần nghe và bài đọc.'
      : exam.sourceNote,
    questions: [...exam.questions, ...vocabularyQuestions, soundQuestion],
  };
}
