export type VocabularyItem = { word: string; meaning: string; example: string };

export const vocabularyByGrade: Record<8 | 9 | 10, VocabularyItem[]> = {
  8: [
    { word: 'leisure', meaning: 'thời gian rảnh', example: 'Reading is my favourite leisure activity.' },
    { word: 'origami', meaning: 'nghệ thuật gấp giấy', example: 'Mai makes animals by doing origami.' },
    { word: 'picturesque', meaning: 'đẹp như tranh', example: 'We stayed in a picturesque village.' },
    { word: 'hospitable', meaning: 'hiếu khách', example: 'The local people were friendly and hospitable.' },
    { word: 'harvest', meaning: 'thu hoạch', example: 'Farmers harvest rice in September.' },
    { word: 'pressure', meaning: 'áp lực', example: 'Talking to a friend can reduce pressure.' },
    { word: 'deadline', meaning: 'hạn hoàn thành', example: 'The project deadline is next Friday.' },
    { word: 'concentrate', meaning: 'tập trung', example: 'I cannot concentrate in a noisy room.' },
    { word: 'custom', meaning: 'phong tục', example: 'Removing shoes is a custom in many homes.' },
    { word: 'tradition', meaning: 'truyền thống', example: 'This family tradition has lasted for generations.' },
    { word: 'habitat', meaning: 'môi trường sống', example: 'The forest is the bear’s natural habitat.' },
    { word: 'endangered', meaning: 'có nguy cơ tuyệt chủng', example: 'The project protects endangered turtles.' },
    { word: 'bargain', meaning: 'món hàng giá hời', example: 'This jacket was a real bargain.' },
    { word: 'receipt', meaning: 'hóa đơn', example: 'Keep the receipt if you need to return it.' },
    { word: 'evacuate', meaning: 'sơ tán', example: 'Residents had to evacuate the flooded area.' },
    { word: 'warning', meaning: 'cảnh báo', example: 'The town received a storm warning.' },
    { word: 'invention', meaning: 'phát minh', example: 'This invention helps families save water.' },
    { word: 'habitable', meaning: 'có thể sinh sống', example: 'Scientists are searching for habitable planets.' },
  ],
  9: [
    { word: 'artisan', meaning: 'nghệ nhân', example: 'The artisan showed us how to make pottery.' },
    { word: 'speciality', meaning: 'đặc sản', example: 'The rice cake is a local speciality.' },
    { word: 'bustling', meaning: 'nhộn nhịp', example: 'The downtown market is always bustling.' },
    { word: 'congested', meaning: 'ùn tắc, đông nghẹt', example: 'The roads become congested at rush hour.' },
    { word: 'balanced', meaning: 'cân bằng', example: 'Teenagers need a balanced diet.' },
    { word: 'overwhelmed', meaning: 'quá tải', example: 'She felt overwhelmed by too many tasks.' },
    { word: 'preserve', meaning: 'gìn giữ', example: 'The museum helps preserve local traditions.' },
    { word: 'extended family', meaning: 'gia đình nhiều thế hệ', example: 'He grew up in an extended family.' },
    { word: 'experience', meaning: 'trải nghiệm', example: 'Camping was an unforgettable experience.' },
    { word: 'anxious', meaning: 'lo lắng', example: 'I felt anxious before speaking in public.' },
    { word: 'reliable', meaning: 'đáng tin cậy', example: 'The metro is fast and reliable.' },
    { word: 'infrastructure', meaning: 'cơ sở hạ tầng', example: 'The city is improving its transport infrastructure.' },
    { word: 'maintenance', meaning: 'việc bảo trì', example: 'Regular maintenance keeps the machine safe.' },
    { word: 'generation', meaning: 'thế hệ', example: 'The skill was passed to the next generation.' },
    { word: 'well-being', meaning: 'trạng thái khỏe mạnh, hạnh phúc', example: 'Sleep is important for teenagers’ well-being.' },
    { word: 'pedestrian', meaning: 'người đi bộ', example: 'The new bridge is safer for pedestrians.' },
    { word: 'craftsmanship', meaning: 'tay nghề thủ công', example: 'Visitors admired the fine craftsmanship.' },
    { word: 'cooperate', meaning: 'hợp tác', example: 'Team members must cooperate to finish the task.' },
  ],
  10: [
    { word: 'breadwinner', meaning: 'người kiếm thu nhập chính', example: 'Her mother is the main breadwinner.' },
    { word: 'household chores', meaning: 'công việc nhà', example: 'Everyone should share household chores.' },
    { word: 'environment', meaning: 'môi trường', example: 'Cycling is better for the environment.' },
    { word: 'reusable', meaning: 'có thể tái sử dụng', example: 'Bring a reusable water bottle.' },
    { word: 'audience', meaning: 'khán giả', example: 'The singer thanked the audience.' },
    { word: 'performance', meaning: 'màn biểu diễn', example: 'The school performance starts at seven.' },
    { word: 'volunteer', meaning: 'tình nguyện viên', example: 'Each volunteer delivered five food packages.' },
    { word: 'donate', meaning: 'quyên góp', example: 'Students donated books to the library.' },
    { word: 'portable', meaning: 'dễ mang theo', example: 'A tablet is light and portable.' },
    { word: 'device', meaning: 'thiết bị', example: 'Turn off the device when it is not in use.' },
    { word: 'opportunity', meaning: 'cơ hội', example: 'Every student deserves an equal opportunity.' },
    { word: 'stereotype', meaning: 'định kiến khuôn mẫu', example: 'Education can challenge a gender stereotype.' },
    { word: 'contribution', meaning: 'sự đóng góp', example: 'She made an important contribution to the project.' },
    { word: 'leadership', meaning: 'khả năng lãnh đạo', example: 'The course develops leadership skills.' },
    { word: 'achievement', meaning: 'thành tựu', example: 'Winning the prize was a major achievement.' },
    { word: 'beneficial', meaning: 'có lợi', example: 'Regular exercise is beneficial to your health.' },
    { word: 'efficient', meaning: 'hiệu quả', example: 'The new machine is more energy-efficient.' },
    { word: 'campaign', meaning: 'chiến dịch', example: 'The campaign encourages people to recycle.' },
  ],
};
